//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_WGEN                        101
#define IDD_BUILDER                     104
#define IDD_CORE                        105
#define IDR_SYSMENU                     106
#define IDR_WGENMENU                    107
#define IDR_SYNCMENU                    108
#define IDR_XCHGMENU                    109
#define IDS_WGEN_RESET                  112
#define IDD_DDESC                       113
#define IDI_DEVICE                      115
#define IDD_TITLE                       116
#define IDI_DIR                         118
#define IDI_MP2                         119
#define IDI_MP4                         120
#define IDD_SYNC                        121
#define IDI_DOWNLOAD                    122
#define IDI_UPLOAD                      123
#define IDI_CHECK                       124
#define IDI_ICON2                       125
#define IDI_UNCHECK                     125
#define IDD_DIALOG1                     126
#define IDD_TBOX                        126
#define IDD_CAMPAIGN                    126
#define IDI_OPEN                        129
#define IDI_RESET                       131
#define IDI_SAVE                        132
#define IDI_XCHG                        133
#define IDI_REFRESH                     134
#define IDI_SYNC                        135
#define IDI_OPENPCDIR                   136
#define IDI_TITLE_XCHG                  137
#define IDI_TITLE_ABOUT                 138
#define IDI_TITLE_PLAY                  139
#define IDI_TITLE_SYNC                  140
#define IDI_TITLE_UPDATE                141
#define IDI_TITLE_WGEN                  142
#define IDB_CANCEL_UNSELECT             144
#define IDB_OK_SELECT                   145
#define IDB_OK_UNSELECT                 146
#define IDB_CANCEL_SELECT               147
#define IDD_HEROEDIT                    148
#define IDI_NEW                         154
#define IDI_ICON3                       155
#define IDI_DEL                         155
#define IDI_RENAME                      157
#define IDI_ICON4                       159
#define IDI_RENAME_DIS                  159
#define IDI_ICON5                       160
#define IDI_RESET_DIS                   160
#define IDI_ICON6                       161
#define IDI_SAVE_DIS                    161
#define IDI_ICON7                       162
#define IDI_DEL_DIS                     162
#define IDI_ICON8                       163
#define IDI_NEW_DIS                     163
#define IDI_ICON9                       164
#define IDI_OPEN_DIS                    164
#define IDI_XCHG_DIS                    165
#define IDI_OPENPCDIR_DIS               166
#define IDI_REFRESH_DIS                 167
#define IDI_SYNC_DIS                    168
#define IDI_TITLE_XCHG_DIS              169
#define IDI_TITLE_ABOUT_DIS             170
#define IDI_TITLE_PLAY_DIS              171
#define IDI_TITLE_SYNC_DIS              172
#define IDI_TITLE_UPDATE_DIS            173
#define IDI_TITLE_WGEN_DIS              174
#define IDI_INI                         176
#define IDI_TXT                         177
#define IDI_UNKNOWN                     178
#define IDI_CANCEL                      179
#define IDI_OK                          180
#define IDI_BACKUP                      183
#define IDI_ICON10                      184
#define IDI_BACKUP_DIS                  184
#define IDI_CF                          186
#define IDI_NETWORK                     187
#define IDB_REBOOT_UNSELECT             190
#define IDB_REBOOT_SELECT               191
#define IDB_REBOOT_UNSELECT_LIGHT       193
#define IDB_REBOOT_DISABLE              194
#define IDB_REFRESH_UNSELECT            196
#define IDB_WELCOME                     200
#define IDI_EDITOR                      201
#define IDD_VISUAL                      203
#define IDI_WITH_SYNC                   210
#define IDI_WITHOUT_SYNC                211
#define IDI_BUILD                       212
#define IDI_BUILD_DIS                   213
#define IDD_CAMPAIGN_MAIN               214
#define IDD_CAMPAIGN_SCENARIO           215
#define IDD_SIDEEDIT                    216
#define IDD_CITYEDIT                    217
#define IDD_TROOPEDIT                   218
#define IDD_FEATURE2EDIT                219
#define IDD_NEWCAMPAIGN                 220
#define IDD_UTYPEEDIT                   221
#define IDD_ATTACKEDIT                  222
#define IDD_MTYPEEDIT                   223
#define IDD_UTYPETROOP                  224
#define IDD_UTYPECITY                   225
#define IDD_UTYPEARTIFICAL              226
#define IDD_UTYPE2EDIT                  227
#define IDD_EVENTEDIT                   228
#define IDD_EVENTFILTER                 229
#define IDD_EVENTUNIT                   230
#define IDD_EVENTKILL                   231
#define IDD_CONDITION                   232
#define IDD_VARIABLE                    233
#define IDD_HAVEUNIT                    234
#define IDD_SETVARIABLE                 235
#define IDD_EVENTJOIN                   236
#define IDI_EVT_COMMAND                 237
#define IDI_EVT_FILTER                  238
#define IDI_EVT_EVENT                   239
#define IDI_EVT_CONDITION               240
#define IDI_EVT_IF                      241
#define IDI_EVT_THEN                    242
#define IDI_ICON1                       243
#define IDI_EVT_ATTRIBUTE               243
#define IDD_VISUAL2                     244
#define IDD_DIALOG2                     245
#define IDD_TACTIC                      245
#define IDD_UTYPE                       246
#define IDD_SCENARIOTREASURE            247
#define IDD_TECHNOLOGY                  248
#define IDD_TECHNOLOGY2                 250
#define IDD_ROAD                        251
#define IDD_UTYPECOMMONER               252
#define IDD_CHARACTER                   253
#define IDD_EVENTENDLEVEL               254
#define IDD_TREASURE                    255
#define IDD_TREASUREEDIT                256
#define IDD_TERRAIN                     257
#define IDD_TERRAINEDIT                 258
#define IDD_BRULE_NONE                  259
#define IDD_TILEEDIT                    260
#define IDD_IMAGEEDIT                   261
#define IDD_BRULE_NORMAL                262
#define IDD_DECREE                      263
#define IDD_FACTION                     264
#define IDD_FACTIONEDIT                 265
#define IDD_EVENTMODIFYUNIT             266
#define IDD_ANIM                        267
#define IDD_ANIMEDIT                    268
#define IDD_ANIMFILTER                  269
#define IDD_ANIMFRAME                   270
#define IDD_ANIMPARTICULAR              271
#define IDI_PARTICULAR                  273
#define IDI_ICON11                      274
#define IDI_CLOCK                       274
#define IDD_CONFIG                      275
#define IDD_OBJECTIVES                  276
#define IDD_EVENTMESSAGE                277
#define IDD_EVENTPRINT                  278
#define IDD_EVENTLABEL                  279
#define IDD_STOREUNIT                   280
#define IDD_FILTERHERO                  281
#define IDD_SIDEHEROS                   282
#define IDD_NEWSCENARIO                 283
#define IDD_MULTIPLAYER                 284
#define IDD_MULTIPLAYERBASE             285
#define IDD_ADJUST                      286
#define IDD_EVENTRENAME                 288
#define IDD_EVENTMODIFYSIDE             289
#define IDD_EVENTMODIFYCITY             290
#define IDD_MSGID                       291
#define IDD_FORMATION                   292
#define IDD_FEATURE                     293
#define IDD_FEATUREEDIT                 294
#define IDD_NOBLE                       295
#define IDD_NOBLEEDIT                   296
#define IDD_PRELUDE                     297
#define IDD_BOOK                        298
#define IDD_TOPICEDIT                   299
#define IDD_RENAME                      300
#define IDD_INTEGRATE                   301
#define IDC_BT_WGEN_EDIT                1034
#define IDC_BT_XCHG_XCHG                1054
#define IDC_BT_XCHG_CANCELXCHG          1055
#define IDC_CMB_WGEN_CFGDESC_SRC        1069
#define IDC_LV_DDESC_EXPLORER           1076
#define IDC_ET_DDESC_SUBAREA            1078
#define IDC_BT_DDESC_BROWSE             1080
#define IDC_LV_SYNC_EXPLORER            1081
#define IDC_LV_SYNC_SYNC                1082
#define IDC_UD_HEROEDIT_LEADERSHIP      1114
#define IDC_ET_CFGBEACON_CURRENTTIMEY   1115
#define IDC_CMB_HEROEDIT_GENDER         1115
#define IDC_UD_CFGBEACON_BESTTIMEX      1116
#define IDC_ET_HEROEDIT_LEADERSHIP      1116
#define IDC_ET_CFGBEACON_BESTTIMEX      1117
#define IDC_CMB_CFGSYS_VIDEO_SOURCE     1117
#define IDC_CMB_HEROEDIT_CONSORT        1117
#define IDC_UD_CFGBEACON_BESTTIMEY      1118
#define IDC_ET_CFGBEACON_BESTTIMEY      1119
#define IDC_ET_SYNC_SUBAREA             1119
#define IDC_CMB_HEROEDIT_AMBITION       1120
#define IDC_ET_HEROEDIT_CATALOG         1121
#define IDC_UD_HEROEDIT_CATALOG         1122
#define IDC_BT_WGEN_REBOOT              1123
#define IDC_ET_HEROEDIT_IMAGE           1123
#define IDC_UD_HEROEDIT_IMAGE           1124
#define IDC_ET_HEROEDIT_LEADERSHIPXP    1125
#define IDC_CHK_UPDATE_AUTOSAVE         1126
#define IDC_UD_HEROEDIT_LEADERSHIPXP    1126
#define IDC_CMB_HEROEDIT_FEATURE        1129
#define IDC_ET_HEROEDIT_ARMS0XP         1130
#define IDC_UD_HEROEDIT_ARMS0XP         1131
#define IDC_CMB_HEROEDIT_ARMS0          1132
#define IDC_ET_HEROEDIT_BIOGRAPHY       1133
#define IDC_CMB_HEROEDIT_ARMS1          1134
#define IDC_CMB_HEROEDIT_ARMS2          1135
#define IDC_CMB_HEROEDIT_ARMS3          1137
#define IDC_CMB_HEROEDIT_ARMS4          1138
#define IDC_CMB_HEROEDIT_FEATURE2       1144
#define IDC_CMB_HEROEDIT_SIDEFEATURE    1144
#define IDC_ET_HEROEDIT_HEART           1145
#define IDC_ET_HEROEDIT_NAME            1146
#define IDC_UD_HEROEDIT_HEART           1147
#define IDC_ET_HEROEDIT_NUMBER          1148
#define IDC_ET_HEROEDIT_SKILL0XP        1149
#define IDC_UD_HEROEDIT_SKILL0XP        1150
#define IDC_ET_HEROEDIT_INTELLECT       1151
#define IDC_UD_HEROEDIT_INTELLECT       1152
#define IDC_ET_HEROEDIT_FORCE           1153
#define IDC_ST_WELCOME                  1154
#define IDC_UD_HEROEDIT_FORCE           1154
#define IDC_ST_MEDIA                    1155
#define IDC_ET_HEROEDIT_POLITICS        1155
#define IDC_UD_HEROEDIT_POLITICS        1156
#define IDC_ET_HEROEDIT_CHARM           1157
#define IDC_UD_HEROEDIT_INTELLECT3      1158
#define IDC_UD_HEROEDIT_CHARM           1158
#define IDC_ET_HEROEDIT_FORCEXP         1159
#define IDC_UD_HEROEDIT_FORCEXP         1160
#define IDC_ET_HEROEDIT_INTELLECTXP     1161
#define IDC_UD_HEROEDIT_INTELLECTXP     1162
#define IDC_ET_HEROEDIT_POLITICSXP      1163
#define IDC_UD_HEROEDIT_POLITICSXP      1164
#define IDC_ET_HEROEDIT_CHARMXP         1165
#define IDC_UD_HEROEDIT_CHARM2          1166
#define IDC_UD_HEROEDIT_CHARMXP         1166
#define IDC_ET_HEROEDIT_ARMS1XP         1167
#define IDC_UD_HEROEDIT_ARMS1XP         1168
#define IDC_ET_HEROEDIT_ARMS2XP         1169
#define IDC_UD_HEROEDIT_ARMS2XP         1170
#define IDC_ET_HEROEDIT_ARMS3XP         1171
#define IDC_ET_DDESC_WWWROOT            1172
#define IDC_UD_HEROEDIT_ARMS3XP         1172
#define IDC_ET_HEROEDIT_ARMS4XP         1173
#define IDC_UD_HEROEDIT_ARMS4XP         1174
#define IDC_ET_HEROEDIT_SKILL2XP        1175
#define IDC_ET_HEROEDIT_SKILL4XP        1175
#define IDC_UD_HEROEDIT_SKILL2XP        1176
#define IDC_UD_HEROEDIT_SKILL3XP        1176
#define IDC_ET_HEROEDIT_SKILL5XP        1177
#define IDC_UD_HEROEDIT_SKILL5XP        1178
#define IDC_CMB_HEROEDIT_SKILL0         1179
#define IDC_CMB_HEROEDIT_SKILL1         1180
#define IDC_CMB_HEROEDIT_SKILL2         1181
#define IDC_CMB_HEROEDIT_SKILL3         1181
#define IDC_CMB_HEROEDIT_SKILL5         1182
#define IDC_CMB_HEROEDIT_TREASURE0      1183
#define IDC_ET_HEROEDIT_SKILL1XP        1184
#define IDC_UD_HEROEDIT_SKILL4XP        1185
#define IDC_CMB_HEROEDIT_TACTIC         1186
#define IDC_UD_HEROEDIT_SKILL1XP        1187
#define IDC_ET_HEROEDIT_SKILL3XP        1188
#define IDC_CMB_HEROEDIT_SKILL4         1189
#define IDC_CMB_HEROEDIT_CHARACTER      1190
#define IDC_CMB_HEROEDIT_UTYPE          1191
#define IDC_ET_HEROEDIT_COST            1192
#define IDC_UD_HEROEDIT_COST            1193
#define IDC_ET_HEROEDIT_SKILL6XP        1194
#define IDC_UD_HEROEDIT_SKILL5XP2       1195
#define IDC_UD_HEROEDIT_SKILL6XP        1195
#define IDC_CMB_HEROEDIT_SKILL6         1196
#define IDC_ET_HEROEDIT_OATH            1197
#define IDC_ET_HEROEDIT_FATHER          1198
#define IDC_ET_HEROEDIT_MOTHER          1199
#define IDC_ET_HEROEDIT_CONSORT         1200
#define IDC_ET_HEROEDIT_INTIMATE        1201
#define IDC_ET_HEROEDIT_INTIMATE2       1202
#define IDC_ET_HEROEDIT_HATE            1202
#define IDC_LV_TBOX_DESC                1204
#define IDC_LV_WGEN_EDITOR              1204
#define IDC_TV_DDESC_EXPLORER           1206
#define IDC_TV_CFG_EXPLORER             1212
#define IDC_ET_WGEN_FIND                1213
#define IDC_TV_UTYPE_EXPLORER           1214
#define IDC_TAB_CAMP_SCENARIO           1215
#define IDC_ET_CAMPMAIN_ID              1217
#define IDC_ET_CAMPMAIN_FILE            1218
#define IDC_ET_CAMPMAIN_NAME            1219
#define IDC_ET_CAMPMAIN_ABBREV_MSGID    1220
#define IDC_ET_CAMPMAIN_ICON            1221
#define IDC_BT_CAMPMAIN_BROWSEICON      1222
#define IDC_ET_CAMPMAIN_IMAGE           1223
#define IDC_BT_CAMPMAIN_BROWSEIMAGE     1224
#define IDC_ET_CAMPMAIN_DESC            1225
#define IDC_CHK_CAMPMAIN_RPGMODE        1226
#define IDC_ET_CAMPMAIN_ABBREV          1227
#define IDC_ET_CAMPMAIN_TEXTDOMAIN      1228
#define IDC_CMB_CAMPMAIN_RANK           1229
#define IDC_CMB_CAMPMAIN_CATALOG        1229
#define IDC_ET_CAMPMAIN_FIRSTSCENARIO   1230
#define IDC_ET_CAMPSCENARIO_FILE        1230
#define IDC_ET_CAMPMAIN_NAME_MSGID      1230
#define IDC_ET_CAMPSCENARIO_ID          1231
#define IDC_ET_CAMPMAIN_DESC_MSGID      1231
#define IDC_ET_CAMPSCENARIO_IDSTATUS    1232
#define IDC_ET_CAMPMAIN_TEXTDOMAINSTATUS 1232
#define IDC_ET_CAMPSCENARIO_TURNS       1233
#define IDC_ET_CAMPSCENARIO_MAP         1234
#define IDC_UD_CAMPSCENARIO_TURNS       1237
#define IDC_ET_OBJECTIVES_SUMMARY       1237
#define IDC_LV_CAMPSCENARIO_SIDE        1240
#define IDC_BT_CAMPSCENARIO_BROWSEMAP   1241
#define IDC_ET_SIDEEDIT_SIDE            1242
#define IDC_ET_SIDEEDIT_NAME            1243
#define IDC_CHK_SIDEEDIT_SHROUD         1244
#define IDC_CHK_SIDEEDIT_CONTROLLER     1244
#define IDC_ET_CAMPSCENARIO_NAME        1244
#define IDC_ET_OBJECTIVESEDIT_SUMMARY_MSGID 1244
#define IDC_ET_OBJECTIVES_SUMMARY_MSGID 1244
#define IDC_CHK_SIDEEDIT_FOG            1245
#define IDC_ET_SIDEEDIT_NAME2           1245
#define IDC_ET_SIDEEDIT_NAME_MSGID      1245
#define IDC_ET_CAMPSCENARIO_NAME_MSGID  1245
#define IDC_CMB_SIDEEDIT_LEADER         1246
#define IDC_LV_CAMPSCENARIO_EVENT       1246
#define IDC_ET_SIDEEDIT_GOLD            1247
#define IDC_LV_CAMPSCENARIO_TREASURE    1247
#define IDC_ET_SIDEEDIT_INCOME          1248
#define IDC_LV_CAMPSCENARIO_ROAD        1248
#define IDC_ET_SIDEEDIT_NAVIGATIONXP    1249
#define IDC_BT_CAMPSCENARIO_OBJECTIVES  1249
#define IDC_CMB_SIDEEDIT_NAVIGATION     1250
#define IDC_BT_CAMPSCENARIO_PRELUDE     1250
#define IDC_BT_SIDEEDIT_ADDCITY         1251
#define IDC_CMB_SIDEEDIT_CONTROLLER     1251
#define IDC_BT_SIDEEDIT_DELETECITY      1252
#define IDC_ET_CITYEDIT_SOLDIERS        1252
#define IDC_CMB_SIDEEDIT_CITYTYPE       1253
#define IDC_CMB_SIDEEDIT_CITYHERO       1254
#define IDC_ET_SIDEEDIT_CITYX           1255
#define IDC_ET_SIDEEDIT_CITYY           1256
#define IDC_LV_SIDEEDIT_TROOP           1257
#define IDC_UD_SIDEEDIT_CITYX           1258
#define IDC_UD_SIDEEDIT_CITYY           1259
#define IDC_LV_SIDEEDIT_CITY2           1260
#define IDC_LV_SIDEEDIT_CITY            1260
#define IDC_CMB_CITYEDIT_HERO           1260
#define IDC_CMB_CITYEDIT_TYPE           1261
#define IDC_LV_SIDEEDIT_FEATURE         1261
#define IDC_ET_CITYEDIT_X               1262
#define IDC_LV_SIDEEDIT_FEATURE2        1262
#define IDC_LV_SIDEEDIT_BUILD           1262
#define IDC_ET_CITYEDIT_Y               1263
#define IDC_UD_CITYEDIT_X               1264
#define IDC_LV_SIDEEDIT_ALLY            1264
#define IDC_UD_CITYEDIT_Y               1265
#define IDC_UD_SIDEEDIT_INCOME          1265
#define IDC_LV_CITYEDIT_TRAITS          1266
#define IDC_LV_CITYEDIT_TRAIT           1266
#define IDC_UD_SIDEEDIT_NAVIGATIONXP    1266
#define IDC_LV_CITYEDIT_SERVICE         1267
#define IDC_LV_CITYEDIT_SERVICE2        1268
#define IDC_LV_CITYEDIT_WANDER          1268
#define IDC_CMB_CITYEDIT_MAYOR          1269
#define IDC_ET_CITYEDIT_EAX             1270
#define IDC_ET_CITYEDIT_EAY             1271
#define IDC_UD_CITYEDIT_EAX             1272
#define IDC_UD_CITYEDIT_EAY             1273
#define IDC_LV_CITYEDIT_EA              1274
#define IDC_BT_CITYEDIT_ADDEA           1275
#define IDC_LV_CITYEDIT_CANDIDATE       1276
#define IDC_LV_CANDIDATEHERO            1276
#define IDC_LV_CITYEDIT_NOTRECRUIT      1277
#define IDC_CMB_CITYEDIT_CHARACTER      1278
#define IDC_CMB_TROOPEDIT_TYPE          1279
#define IDC_BT_CITYEDIT_ADDEA2          1279
#define IDC_ET_TROOPEDIT_X              1280
#define IDC_UD_TROOPEDIT_X              1281
#define IDC_ET_TROOPEDIT_Y              1282
#define IDC_UD_TROOPEDIT_Y              1283
#define IDC_LV_TROOPEDIT_CANDIDATE      1284
#define IDC_LV_TROOPEDIT_HERO           1285
#define IDC_CMB_TROOPEDIT_CITY          1286
#define IDC_LV_TROOPEDIT_TRAIT          1287
#define IDC_CMB_FEATUREEDIT_ARMS        1288
#define IDC_CMB_TROOPEDIT_CHARACTER     1288
#define IDC_CMB_FEATUREEDIT_LEVEL       1289
#define IDC_UD_SIDEEDIT_GOLD            1289
#define IDC_CMB_FEATUREEDIT_FEATURE     1290
#define IDC_ET_NEWCAMP_ID               1290
#define IDC_UD_CITYEDIT_SOLDIERS        1290
#define IDC_ET_NEWCAMP_FIRSTSCENARIOID  1291
#define IDC_COMBO1                      1291
#define IDC_CMB_CAMPSCENARIO_NEXTSCENARIO 1291
#define IDC_CMB_UTYPEEDIT_TYPE          1291
#define IDC_CMB_MTYPEEDIT_TYPE          1291
#define IDC_CMB_UTYPEARTIFICAL_MASTER   1291
#define IDC_CMB_EVENTFILTER_MASTERHERO  1291
#define IDC_CMB_EVENTUNIT_              1291
#define IDC_CMB_EVENTUNIT_TYPE          1291
#define IDC_CMB_VARIABLE_OP             1291
#define IDC_CMB_TREASURE_TREASURE       1291
#define IDC_CMB_SYNC_LANGUAGE           1291
#define IDC_CMB_ROAD_CITY1              1291
#define IDC_CMB_TREASUREEDIT_FEATURE    1291
#define IDC_CMB_ANIMFILTER_ID           1291
#define IDC_CMB_EVENTRENAME_NUMBER      1291
#define IDC_CMB_BOOKS                   1291
#define IDC_CMB_INTEGRATE_FORMATER      1291
#define IDC_ET_NEWCAMP_DESC             1292
#define IDC_CMB_CAMPMAIN_FIRSTSCENARIO  1292
#define IDC_CMB_UTYPEEDIT_LEVEL         1292
#define IDC_CMB_ATTACKEDIT_RANGE        1292
#define IDC_CMB_UTYPEARTIFICAL_GUARD    1292
#define IDC_CMB_EVENTUNIT_CITY          1292
#define IDC_CMB_EVENTFILTER_CITY        1292
#define IDC_CMB_ROAD_CITY2              1292
#define IDC_CMB_CAMPSCENARIO_DUEL       1292
#define IDC_CMB_ANIMFILTER_RANGE        1292
#define IDC_CMB_VARIABLE_LOGIC          1292
#define IDC_CMB_CONDITION_LOGIC         1292
#define IDC_ET_UTYPEEDIT_FILE           1293
#define IDC_CMB_ATTACKEDIT_TYPE         1293
#define IDC_CMB_EVENTUNIT_SIDE          1293
#define IDC_CMB_CAMPMAIN_MODE           1293
#define IDC_CMB_EVENTFILTER_SIDE        1293
#define IDC_CMB_ANIMFILTER_ALIGN        1293
#define IDC_ET_NEWCAMP_FIRSTSCENARIODESC 1294
#define IDC_ET_UTYPEEDIT_ID             1294
#define IDC_CMB_EVENTFILTER_HP          1294
#define IDC_CMB_ANIMFILTER_FEATURE      1294
#define IDC_ET_UTYPEEDIT_IDSTATUS       1295
#define IDC_CMB_EVENTFILTER_CONTROLLER  1295
#define IDC_LV_UTYPEEDIT_ADVANCESTO     1296
#define IDC_ET_UTYPEEDIT_NAME_MSGID     1297
#define IDC_ET_UTYPEEDIT_NAME           1298
#define IDC_ET_UTYPEEDIT_RACE           1299
#define IDC_LV_UTYPEEDIT_ABILITIES      1300
#define IDC_ET_UTYPEEDIT_HP             1301
#define IDC_UD_UTYPEEDIT_HP             1302
#define IDC_ET_UTYPEEDIT_XP             1303
#define IDC_ET_ATTACKEDIT_TEXTDOMAIN    1303
#define IDC_UD_UTYPEEDIT_XP             1304
#define IDC_ET_ATTACKEDIT_ID            1304
#define IDC_ET_ATTACKEDIT_IDSTATUS      1305
#define IDC_ET_ATTACKEDIT_NAME_MSGID    1306
#define IDC_CMB_UTYPEEDIT_ALIGNMENT     1307
#define IDC_ET_ATTACKEDIT_NAME          1307
#define IDC_ET_UTYPEEDIT_COST           1308
#define IDC_LV_ATTACKEDIT_SPECIALS      1308
#define IDC_UD_UTYPEEDIT_COST           1309
#define IDC_ET_ATTACKEDIT_DAMAGE        1309
#define IDC_LV_UTYPEEDIT_ATTACK         1310
#define IDC_UD_ATTACKEDIT_DAMAGE        1310
#define IDC_ET_UTYPEEDIT_DESC_MSGID     1311
#define IDC_ET_ATTACKEDIT_NUMBER        1311
#define IDC_ET_UTYPEEDIT_DESC           1312
#define IDC_UD_ATTACKEDIT_NUMBER        1312
#define IDC_ET_UTYPEEDIT_TEXTDOMAIN     1313
#define IDC_ET_ATTACKEDIT_ICON          1313
#define IDC_ET_UTYPEEDIT_TEXTDOMAINSTATUS 1314
#define IDC_BT_ATTACKEDIT_BROWSEICON    1314
#define IDC_CMB_UTYPEEDIT_ARMS          1315
#define IDC_LV_UTYPEEDIT_MTYPE          1316
#define IDC_ET_UTYPEEDIT_TYPE           1317
#define IDC_LV_MTYPEEDIT_RESISTANCE     1318
#define IDC_ET_UTYPEEDIT_ICON           1318
#define IDC_ET_MTYPEEDIT_NAME           1319
#define IDC_LV_BRULENONE_IMAGE          1319
#define IDC_ET_UTYPEEDIT_MOVEMENTSOUND  1319
#define IDC_ET_MTYPEEDIT_VALUE          1320
#define IDC_ET_UTYPEEDIT_IDLESOUND      1320
#define IDC_UD_MTYPEEDIT_VALUE          1321
#define IDC_CHK_UTYPEEDIT_ZOC           1322
#define IDC_LV_MTYPEEDIT_DEFENSE        1322
#define IDC_LV_MTYPEEDIT_MOVEMENTCOSTS  1323
#define IDC_STATIC_UTYPEEDIT_ABILITIES  1324
#define IDC_STATIC_UTYPEEDIT_ADVANCESTO 1325
#define IDC_STATIC_ATTACKEDIT_SPECIALS  1325
#define IDC_ET_UTYPETROOP_MOVEMENT      1326
#define IDC_CMB_UTYPETROOP_CHARACTER    1327
#define IDC_UD_UTYPETROOP_MOVEMENT      1328
#define IDC_CHK_UTYPETROOP_LANDWALL     1329
#define IDC_BT_UTYPEEDIT_SPECIAL        1330
#define IDC_CHK_UTYPETROOP_LEADER       1330
#define IDC_CMB_UTYPETROOP_REQUIRE      1330
#define IDC_ET_UTYPECITY_TURNEXPERIENCE 1331
#define IDC_ET_UTYPETROOP_MAXMOVEMENT   1331
#define IDC_BT_UTYPEEDIT_BROWSEMOVEMENTSOUND 1331
#define IDC_UD_UTYPECITY_TURNEXPERIENCE 1332
#define IDC_UD_UTYPETROOP_MAXMOVEMENT   1332
#define IDC_BT_UTYPEEDIT_BROWSEIDLESOUND 1332
#define IDC_ET_UTYPEARTIFICAL_HEAL      1333
#define IDC_ET_UTYPECITY_HEAL           1333
#define IDC_UD_UTYPEARTIFICAL_HEAL      1334
#define IDC_UD_UTYPECITY_HEAL           1334
#define IDC_ET_UTYPEARTIFICAL_INCOME    1335
#define IDC_ET_UTYPEEDIT_MELEEINCREASE  1335
#define IDC_UD_UTYPEARTIFICAL_INCOME    1336
#define IDC_UD_UTYPEEDIT_MELEEINCREASE  1336
#define IDC_ET_UTYPEEDIT_RANGEDINCREASE 1337
#define IDC_STATIC_CITYEDIT_NOTRECRUIT  1337
#define IDC_UD_UTYPEEDIT_RANGEDINCREASE 1338
#define IDC_TV_EVENTEDIT_EXPLORER       1338
#define IDC_ET_UTYPEEDIT_CASTINCREASE   1339
#define IDC_LV_EVENTFILTER_MUSTHEROS    1339
#define IDC_UD_UTYPEEDIT_CASTINCREASE   1340
#define IDC_STATIC_EVENTFILTER_MUSTHEROS 1340
#define IDC_STATIC_MUSTHEROS            1340
#define IDC_LV_EVENTUNIT_HEROSARMY      1341
#define IDC_STATIC_EVENTUNIT_HEROSARMY  1342
#define IDC_LV_EVENTUNIT_VARIABLE       1343
#define IDC_LV_EVENT_VARIABLE           1343
#define IDC_EDIT1                       1344
#define IDC_ET_EVENTUNIT_HEROSARMY      1344
#define IDC_ET_VARIABLE_LEFT            1344
#define IDC_ET_HAVEUNIT_FILTER          1344
#define IDC_ET_TERRAINEDIT_STRING       1344
#define IDC_ET_BRULENONE_MAP            1344
#define IDC_ET_TILEEDIT_POS             1344
#define IDC_ET_BRULENORMAL_PARAM0       1344
#define IDC_ET_EVENTMODIFYUNIT_EFFECT   1344
#define IDC_LV_EVENTKILL_SIDE           1344
#define IDC_ET_ADJUST_THIS              1344
#define IDC_ET_TOPICEDIT_TEXT           1344
#define IDC_ET_RENAME_NAME              1344
#define IDC_ET_EVENTUNIT_TYPE           1345
#define IDC_ET_VARIABLE_RIGHT           1345
#define IDC_ET_TERRAINEDIT_ID           1345
#define IDC_ET_TILEEDIT_TYPE            1345
#define IDC_ET_BRULENORMAL_PARAM1       1345
#define IDC_ET_TOPICEDIT_TEXTMSGID      1345
#define IDC_ET_TOPICEDIT_TEXT_MSGID     1345
#define IDC_ET_RENAME_STATUS            1345
#define IDC_ET_EVENTUNIT_CITY           1346
#define IDC_ET_TERRAINEDIT_STRINGSTATUS 1346
#define IDC_ET_TILEEDIT_FLAG            1346
#define IDC_ET_BRULENORMAL_PARAM2       1346
#define IDC_ET_EVENTUNIT_SIDE           1347
#define IDC_ET_TERRAINEDIT_NAME_MSGID   1347
#define IDC_ET_BRULENORMAL_PARAM3       1347
#define IDC_ET_EVENTUNIT_X              1348
#define IDC_ET_TERRAINEDIT_NAMESTATUS   1348
#define IDC_ET_TERRAINEDIT_NAME         1348
#define IDC_ET_BRULENORMAL_PARAM4       1348
#define IDC_UD_EVENTUNIT_X              1349
#define IDC_ET_TERRAINEDIT_ALIAS        1349
#define IDC_ET_BRULENORMAL_PARAM5       1349
#define IDC_ET_EVENTUNIT_Y              1350
#define IDC_ET_TERRAINEDIT_ALIASSTATUS  1350
#define IDC_ET_BRULENORMAL_PARAM6       1350
#define IDC_UD_EVENTUNIT_Y              1351
#define IDC_ET_TERRAINEDIT_MVTALIAS     1351
#define IDC_ET_BRULENORMAL_PARAM7       1351
#define IDC_ET_EVENTUNIT_VARX           1352
#define IDC_ET_TERRAINEDIT_MVTALIASSTATUS 1352
#define IDC_ET_BRULENORMAL_PARAM8       1352
#define IDC_ET_EVENTUNIT_VARY           1353
#define IDC_ET_TERRAINEDIT_DEFALIAS     1353
#define IDC_ET_BRULENORMAL_PARAM9       1353
#define IDC_ET_EVENTKILL_HERO           1353
#define IDC_LV_EVENTKILL_VARIABLE       1354
#define IDC_STATIC_EVENTUNIT_HEROSARMY2 1354
#define IDC_ET_TERRAINEDIT_DEFALIASSTATUS 1354
#define IDC_ET_BRULENORMAL_POSTFIX      1354
#define IDC_ET_EVENTKILL_SIDE           1354
#define IDC_STATIC_EVENTUNIT_HEROSARMY3 1355
#define IDC_ET_EVENTUNIT_STATE          1355
#define IDC_TAB_CONDITION_CONDITION     1356
#define IDC_CMB_EVENTJOIN_JOIN          1356
#define IDC_ET_EVENTJOIN_JOIN           1357
#define IDC_BT_HAVEUNIT_FILTER          1358
#define IDC_LV_VARIABLE_ENV             1359
#define IDC_ET_SETVARIABLE_NAME         1360
#define IDC_CMB_SETVARIABLE_OP          1361
#define IDC_ET_EVENT_VALUE              1362
#define IDC_LV_SETVARIABLE_ENV          1363
#define IDC_ET_SETVARIABLE_NAMESTATUS   1364
#define IDC_ET_EVENTJOIN_MASTERHERO     1364
#define IDC_CMB_EVENTJOIN_MASTERHERO    1365
#define IDC_ET_EVENT_VALUE_MSGID        1365
#define IDC_LV_EVENTJOIN_VARIABLE       1366
#define IDC_ET_EVENT_TEXTDOMAIN         1366
#define IDC_LIST1                       1367
#define IDC_LV_VISUAL2_EXPLORER         1367
#define IDC_LV_TREASURE_EXPLORER        1367
#define IDC_TAB_CORE_SECTION            1368
#define IDC_TV_TACTIC_ATOM              1370
#define IDC_TV_TACTIC_COMPLEX           1371
#define IDC_ET_TREASURE_COUNT           1371
#define IDC_UD_TREASURE_COUNT           1372
#define IDC_STATIC_SYNC_LANGUAGE        1373
#define IDC_STATIC_NUMBER               1374
#define IDC_STATIC_PICTURENUMBER        1375
#define IDC_STATIC_NAME                 1376
#define IDC_STATIC_GENDER               1377
#define IDC_STATIC_ALIAS                1377
#define IDC_STATIC_CENTER               1377
#define IDC_STATIC_HOST                 1377
#define IDC_STATIC_CATALOG              1378
#define IDC_STATIC_MVTALIAS             1378
#define IDC_STATIC_URL                  1378
#define IDC_STATIC_HEART                1379
#define IDC_STATIC_DEFALIAS             1379
#define IDC_STATIC_LEADERSHIP           1380
#define IDC_STATIC_HEIGHT               1380
#define IDC_STATIC_FORCE                1381
#define IDC_STATIC_SUBMERGE             1381
#define IDC_STATIC_INTELLECT            1382
#define IDC_STATIC_LIGHT                1382
#define IDC_STATIC_POLITICS             1383
#define IDC_STATIC_HEALS                1383
#define IDC_STATIC_CHARM                1384
#define IDC_STATIC_GROUP                1384
#define IDC_STATIC_EXPERIENCE           1385
#define IDC_STATIC_DEFAULTBASE          1385
#define IDC_STATIC_ARMS                 1386
#define IDC_STATIC_SYMBOLIMAGE          1386
#define IDC_STATIC_SKILL                1387
#define IDC_STATIC_EDITORIMAGE          1387
#define IDC_STATIC_ARMS0                1388
#define IDC_STATIC_ARMS1                1389
#define IDC_STATIC_ARMS2                1390
#define IDC_STATIC_ARMS3                1391
#define IDC_STATIC_ARMS4                1392
#define IDC_STATIC_SKILL0               1393
#define IDC_STATIC_SKILL3               1394
#define IDC_STATIC_SKILL4               1395
#define IDC_STATIC_SKILL5               1396
#define IDC_STATIC_RELATION             1397
#define IDC_STATIC_PARENT               1398
#define IDC_STATIC_CONSORT              1399
#define IDC_STATIC_OATH                 1400
#define IDC_STATIC_INTIMATE             1401
#define IDC_STATIC_HATE                 1402
#define IDC_STATIC_FEATURE              1403
#define IDC_STATIC_SIDEFEATURE          1404
#define IDC_STATIC_SKILL6               1405
#define IDC_STATIC_TACTIC               1406
#define IDC_STATIC_BIOGRAPHY            1407
#define IDC_STATIC_TREASURE             1408
#define IDC_STATIC_FILE                 1409
#define IDC_STATIC_SKILL1               1409
#define IDC_STATIC_DOMAIN               1410
#define IDC_STATIC_ROAD                 1410
#define IDC_STATIC_UTYPE                1410
#define IDC_STATIC_ID                   1411
#define IDC_STATIC_DESCRIPTION          1412
#define IDC_STATIC_ALIGN                1412
#define IDC_STATIC_TYPE                 1413
#define IDC_STATIC_LEVEL                1414
#define IDC_STATIC_FAMILY               1414
#define IDC_STATIC_RACE                 1415
#define IDC_STATIC_ALIGNMENT            1416
#define IDC_STATIC_MTYPE                1417
#define IDC_STATIC_COST                 1418
#define IDC_STATIC_GOLD                 1419
#define IDC_STATIC_ATTACK               1420
#define IDC_STATIC_SOLDIERS             1420
#define IDC_STATIC_MOVEMENT             1421
#define IDC_STATIC_CHARACTER            1422
#define IDC_STATIC_HEAL                 1423
#define IDC_STATIC_REQUIRE              1423
#define IDC_STATIC_GUARD                1424
#define IDC_STATIC_INCOME               1425
#define IDC_STATIC_TURNEXPERIENCE       1426
#define IDC_STATIC_RESISTANCE           1427
#define IDC_STATIC_DEFEND               1428
#define IDC_STATIC_MOVEMENTCOST         1429
#define IDC_STATIC_TIP                  1430
#define IDC_STATIC_ICON                 1431
#define IDC_STATIC_RANGE                1432
#define IDC_STATIC_MOVEMENTSOUND        1432
#define IDC_STATIC_DAMAGE               1433
#define IDC_STATIC_IDLESOUND            1433
#define IDC_STATIC_MELEE                1434
#define IDC_STATIC_RANGED               1435
#define IDC_STATIC_CAST                 1436
#define IDC_STATIC_ABBREVIATION         1437
#define IDC_STATIC_RANK                 1438
#define IDC_STATIC_FIRSTSCENARIO        1439
#define IDC_STATIC_IMAGE                1440
#define IDC_STATIC_MAP                  1441
#define IDC_STATIC_MODE                 1441
#define IDC_STATIC_HALO                 1441
#define IDC_STATIC_TURNS                1442
#define IDC_STATIC_TILE                 1442
#define IDC_STATIC_HALOX                1442
#define IDC_STATIC_VARIABLE             1442
#define IDC_STATIC_HALOY                1443
#define IDC_STATIC_WIN                  1444
#define IDC_STATIC_LOSE                 1445
#define IDC_STATIC_SOUND                1445
#define IDC_STATIC_NEXTSCENARIO         1446
#define IDC_STATIC_X                    1446
#define IDC_STATIC_LEADER               1447
#define IDC_STATIC_DUEL                 1447
#define IDC_STATIC_Y                    1447
#define IDC_STATIC_IMAGEDIAGONAL        1448
#define IDC_STATIC_FINDIN               1448
#define IDC_STATIC_CITY                 1449
#define IDC_STATIC_STEXT                1449
#define IDC_STATIC_TROOP                1450
#define IDC_STATIC_ALPHA                1450
#define IDC_STATIC_MERITORIOUS          1450
#define IDC_STATIC_MAYOR                1451
#define IDC_STATIC_TECHNOLOGY           1451
#define IDC_STATIC_IMAGEMOD             1451
#define IDC_STATIC_COORDINATE           1452
#define IDC_STATIC_OFFSET_Y             1452
#define IDC_STATIC_TRAITS               1453
#define IDC_STATIC_IMAGEHORIZONTAL      1453
#define IDC_STATIC_HERO                 1454
#define IDC_STATIC_CANDIDATE            1455
#define IDC_STATIC_OFFICE               1456
#define IDC_STATIC_ITEM                 1456
#define IDC_STATIC_WANDER               1457
#define IDC_STATIC_EA                   1458
#define IDC_STATIC_EACOORDINATE         1459
#define IDC_STATIC_TROOPHERO            1460
#define IDC_STATIC_TEMPLATE             1461
#define IDC_STATIC_CAMPAIGNID           1462
#define IDC_STATIC_SCENARIOID           1463
#define IDC_TV_TECHNOLOGY_ATOM          1464
#define IDC_TV_TECHNOLOGY2_EXPOLORER    1464
#define IDC_TV_TECHNOLOGY2_EXPLORER     1464
#define IDC_TV_TECHNOLOGY_COMPLEX       1465
#define IDC_STATIC_NAVIGATION           1466
#define IDC_TV_TECHNOLOGY_EXPLORER      1466
#define IDC_STATIC_MAXIMUM              1467
#define IDC_STATIC_BUILD                1467
#define IDC_STATIC_UNRESTRAINT          1468
#define IDC_STATIC_ALLY                 1468
#define IDC_STATIC_CITY1                1469
#define IDC_STATIC_CITY2                1470
#define IDC_ET_UTYPECOMMONER_MOVEMENT   1470
#define IDC_UD_UTYPECOMMONER_MOVEMENT   1471
#define IDC_ET_UTYPECOMMONER_MAXMOVEMENT 1472
#define IDC_UD_UTYPECOMMONER_MAXMOVEMENT 1473
#define IDC_CMB_UTYPECOMMONER_MASTER    1474
#define IDC_ET_UTYPECOMMONER_INCOME     1475
#define IDC_UD_UTYPECOMMONER_INCOME     1476
#define IDC_TV_CHARACTER_ATOM           1477
#define IDC_TV_CHARACTER_COMPLEX        1478
#define IDC_CHK_UTYPECITY_TOUCHDIRS     1479
#define IDC_CMB_EVENTENDLEVEL_RESULT    1481
#define IDC_STATIC_REMARK               1482
#define IDC_LV_TERRAIN_EDITOR           1483
#define IDC_LV_BUILDER_EXPLORER         1483
#define IDC_LV_TERRAIN_EXPLORER         1484
#define IDC_STATIC_STRING               1485
#define IDC_LV_BRULENONE_TILE           1486
#define IDC_STATIC_POS                  1487
#define IDC_STATIC_FLAG                 1488
#define IDC_UD_TILEEDIT_POS             1489
#define IDC_STATIC_LAYER                1490
#define IDC_ET_IMAGEEDIT_LAYER          1491
#define IDC_STATIC_ZOOM_X               1491
#define IDC_STATIC_PARAM0               1492
#define IDC_STATIC_ZOOM_Y               1492
#define IDC_ET_IMAGEEDIT_NAME           1493
#define IDC_STATIC_PARAM1               1493
#define IDC_ET_IMAGEEDIT_CENTER         1494
#define IDC_STATIC_PARAM2               1494
#define IDC_STATIC_PARAM3               1495
#define IDC_STATIC_PARAM4               1496
#define IDC_STATIC_PARAM5               1497
#define IDC_STATIC_PARAM6               1498
#define IDC_STATIC_PARAM7               1499
#define IDC_STATIC_PARAM8               1500
#define IDC_TV_DECREE_ATOM              1500
#define IDC_STATIC_PARAM9               1501
#define IDC_TV_DECREE_COMPLEX           1501
#define IDC_ET_BRULENORMAL_DESCRIPTION  1502
#define IDC_LV_FACTION_CANDIDATE        1502
#define IDC_STATIC_POSTFIX              1503
#define IDC_LV_FACTION_SERVICE          1503
#define IDC_LV_FACTION_WANDER           1504
#define IDC_LV_FACTION_EXPLORER         1505
#define IDC_CMB_FACTIONEDIT_LEADER      1506
#define IDC_LV_FEATURE_COMPLEX          1506
#define IDC_CMB_FACTIONEDIT_CITY        1507
#define IDC_ET_EVENTMODIFYUNIT_MASTERHERO 1508
#define IDC_CMB_EVENTMODIFYUNIT_MASTERHERO 1509
#define IDC_CHK_HEROEDIT_ROBBER         1510
#define IDC_CHECK2                      1511
#define IDC_CHK_ROAM                    1511
#define IDC_CHK_HEROEDIT_ROAM           1511
#define IDC_LV_ANIM_EXPLORER            1511
#define IDC_CHK_ANIMFRAME_VFLIP         1511
#define IDC_CHK_ANIMPARTICULAR_CYCLES   1511
#define IDC_TV_ANIMEDIT_EXPLORER        1512
#define IDC_CHK_HEROEDIT_ROBBER2        1512
#define IDC_CHK_HEROEDIT_EMPLOYEE       1512
#define IDC_CHK_ANIMFRAME_DISHFLIP      1512
#define IDC_CHK_ANIMFRAME_HFLIP         1512
#define IDC_STATIC_MATCH                1513
#define IDC_CHK_HEROEDIT_NPC            1513
#define IDC_ET_ANIMEDIT_ID              1514
#define IDC_ET_ANIMEDIT_ALIASSTATUS     1515
#define IDC_CHK_ANIMFILTER_HIT          1516
#define IDC_CHK_ANIMFILTER_MISS         1517
#define IDC_CHK_ANIMFILTER_KILL         1518
#define IDC_CHK_ANIMFILTER_N            1519
#define IDC_CHK_ANIMFILTER_NE           1520
#define IDC_CHK_ANIMFILTER_NW           1521
#define IDC_CHK_ANIMFILTER_S            1522
#define IDC_CHK_ANIMFILTER_SE           1523
#define IDC_CHK_ANIMFILTER_SW           1524
#define IDC_CHK_ANIMFILTER_BLADE        1525
#define IDC_ET_ANIMFRAME_IMAGE          1526
#define IDC_CHK_ANIMFILTER_PIERCE       1526
#define IDC_ET_ANIMFRAME_HALO           1527
#define IDC_CHK_ANIMFILTER_IMPACT       1527
#define IDC_STATIC_DURATION             1528
#define IDC_CHK_ANIMFILTER_ARCHERY      1528
#define IDC_ET_ANIMFRAME_DURATION       1529
#define IDC_CHK_ANIMFILTER_COLLAPSE     1529
#define IDC_UD_ANIMFRAME_DURATION       1530
#define IDC_CHK_ANIMFILTER_ARCANE       1530
#define IDC_ET_ANIMFRAME_HALOX          1531
#define IDC_STATIC_STARTTIME            1531
#define IDC_CHK_ANIMFILTER_FIRE         1531
#define IDC_ET_ANIMFRAME_HALOY          1532
#define IDC_ET_ANIMPARTICULAR_STARTTIME 1532
#define IDC_CHK_ANIMFILTER_COLD         1532
#define IDC_UD_ANIMPARTICULAR_STARTTIME 1533
#define IDC_ET_ANIMFRAME_OFFSET_X       1533
#define IDC_ET_ANIMFRAME_SOUND          1534
#define IDC_ET_ANIMPARTICULAR_OFFSET_X  1534
#define IDC_ET_ANIMFRAME_X              1535
#define IDC_ET_ANIMPARTICULAR_OFFSET2   1535
#define IDC_ET_ANIMPARTICULAR_OFFSET_Y  1535
#define IDC_ET_ANIMFRAME_Y              1536
#define IDC_ET_ANIMFRAME_IMAGEDIAGONAL  1537
#define IDC_ET_ANIMPARTICULAR_X         1537
#define IDC_ET_ANIMFRAME_STEXT          1538
#define IDC_ET_ANIMPARTICULAR_Y         1538
#define IDC_STATIC_FONTSIZE             1539
#define IDC_CHECK1                      1539
#define IDC_CHK_ANIMPARTICULAR_SCREENMODE 1539
#define IDC_CHK_EVENTFILTER_NOT         1539
#define IDC_CHK_CAMPSCENARIO_ENEMYNOCITY 1539
#define IDC_CHK_SIDEEDIT_ALLOWPLAYER    1539
#define IDC_CHK_ATTACKEDIT_ATTACKWEIGHT 1539
#define IDC_CHK_EVENTMESSAGE_YESNO      1539
#define IDC_CHK_EVENTMODIFYSIDE_EXCLUDEHUMAN 1539
#define IDC_CHK_EVENTKILL_DIRECTHERO    1539
#define IDC_ET_ANIMPARTICULAR_LAYER     1539
#define IDC_CHK_CAMPMAIN_SUBCONTINENT   1539
#define IDC_ET_ANIMFRAME_FONTSIZE       1540
#define IDC_CHK_EVENTFILTER_HP          1540
#define IDC_CHK_CAMPSCENARIO_FALLENTOUNSTAGE 1540
#define IDC_UD_ANIMPARTICULAR_LAYER     1540
#define IDC_UD_ANIMFRAME_FONTSIZE       1541
#define IDC_CHK_CAMPSCENARIO_TENT       1541
#define IDC_ET_ANIMPARTICULAR_ZOOM_X    1541
#define IDC_ET_ANIMFRAME_ALPHA          1542
#define IDC_UD_ANIMPARTICULAR_ZOOM_X    1542
#define IDC_ET_ANIMFRAME_IMAGEMOD       1543
#define IDC_ET_ANIMPARTICULAR_ZOOM_Y    1543
#define IDC_LV_ANIMFRAME_VARIABLE       1544
#define IDC_UD_ANIMPARTICULAR_ZOOM_Y    1544
#define IDC_STATIC_PREFIX               1545
#define IDC_ET_ANIMFRAME_OFFSET_Y       1545
#define IDC_ET_ANIMPARTICULAR_PREFIX    1546
#define IDC_STATIC_TEXTCOLOR            1546
#define IDC_ET_IDC_ET_ANIMPARTICULAR_PREFIXSTATUS 1547
#define IDC_ET_ANIMPARTICULAR_PREFIXSTATUS 1547
#define IDC_ET_ANIMFRAME_RED            1547
#define IDC_ET_ANIMPARTICULAR_TAG       1548
#define IDC_STATIC_BBSSERVER            1548
#define IDC_UD_ANIMFRAME_RED            1548
#define IDC_ET_ANIMFRAME_GREEN          1549
#define IDC_ET_CONFIG_NAME              1550
#define IDC_UD_ANIMFRAME_GREEN          1550
#define IDC_ET_CONFIG_HOST              1551
#define IDC_ET_ANIMFRAME_BLUE           1551
#define IDC_ET_CONFIG_PORT              1552
#define IDC_UD_ANIMFRAME_BLUE           1552
#define IDC_UD_CONFIG_PORT              1553
#define IDC_STATIC_TEXTCOLOR2           1553
#define IDC_ET_ANIMFRAME_IMAGEHORIZONTAL 1553
#define IDC_ET_CONFIG_URL               1554
#define IDC_ET_CONFIG_TEXTDOMAIN        1555
#define IDC_ET_CONFIG_DOMAIN            1555
#define IDC_LV_SIDEEDIT_RESERVE         1555
#define IDC_STATIC_RESERVE              1556
#define IDC_STATIC_SUMMARY              1557
#define IDC_ET_EVENTMESSAGE_CAPTION     1563
#define IDC_ET_EVENTMESSAGE_MESSAGE     1564
#define IDC_ET_EVENTMESSAGE_HERO        1565
#define IDC_CMB_EVENTMESSAGE_HERO       1566
#define IDC_ET_EVENTMESSAGE_MESSAGE_MSGID 1567
#define IDC_ET_EVENTMESSAGE_CAPTION_MSGID 1568
#define IDC_ET_EVENTPRINT_FONTSIZE      1569
#define IDC_UD_EVENTPRINT_FONTSIZE      1570
#define IDC_ET_EVENTPRINT_DURATION      1571
#define IDC_UD_EVENTPRINT_DURATION      1572
#define IDC_STATIC_TEXT                 1573
#define IDC_ET_EVENTPRINT_TEXT_MSGID    1574
#define IDC_ET_EVENTPRINT_TEXT          1575
#define IDC_ET_EVENTPRINT_RED           1576
#define IDC_UD_EVENTPRINT_RED           1577
#define IDC_ET_EVENTPRINT_GREEN         1578
#define IDC_UD_EVENTPRINT_GREEN         1579
#define IDC_ET_EVENTPRINT_BLUE          1580
#define IDC_UD_EVENTPRINT_GREEN2        1581
#define IDC_UD_EVENTPRINT_BLUE          1581
#define IDC_STATIC_COLOR                1582
#define IDC_STATIC_SIDE                 1583
#define IDC_STATIC_COOR                 1584
#define IDC_ET_EVENTLABEL_X             1585
#define IDC_STATIC_HP                   1585
#define IDC_ET_EVENTLABEL_Y             1586
#define IDC_STATIC_CONTROLLER           1586
#define IDC_UD_EVENTLABEL_X             1587
#define IDC_UD_EVENTLABEL_Y             1588
#define IDC_ET_EVENTLABEL_TEXT_MSGID    1589
#define IDC_ET_EVENTLABEL_TEXT          1590
#define IDC_STATIC_FILTERLOCATION       1591
#define IDC_ET_EVENTFILTER_X            1592
#define IDC_UD_EVENTFILTER_X            1593
#define IDC_ET_EVENTFILTER_Y            1594
#define IDC_UD_EVENTFILTER_Y            1595
#define IDC_ET_EVENTFILTER_X2           1596
#define IDC_ET_EVENTFILTER_FINDIN       1596
#define IDC_LV_CONDITION_EXPLORER       1596
#define IDC_STATIC_LOGIC                1597
#define IDC_ET_EVENTFILTER_X3           1597
#define IDC_ET_EVENTFILTER_TYPE         1597
#define IDC_LV_EVENTUNIT_TRAIT          1598
#define IDC_STATIC_COUNT                1598
#define IDC_ET_EVENTFILTER_MUSTHEROS    1598
#define IDC_ET_HAVEUNIT_COUNT           1599
#define IDC_ET_EVENTFILTER_HP           1599
#define IDC_BT_STOREUNIT_FILTER         1600
#define IDC_ET_EVENTFILTER_FAMILY       1600
#define IDC_ET_STOREUNIT_VARIABLE       1601
#define IDC_ET_STOREUNIT_FILTER         1602
#define IDC_CMB_STOREUNIT_MODE          1603
#define IDC_CMB_FILTERHERO_NUMBER       1604
#define IDC_LV_SIDEHEROS_SIDE           1607
#define IDC_ET_SIDEHEROS_SIDE           1608
#define IDC_LV_SIDEHEROS_CANDIDATE      1609
#define IDC_LV_SIDEHEROS_SERVICE        1610
#define IDC_LV_SIDEHEROS_HEROS          1610
#define IDC_STATIC_SERVICE              1611
#define IDC_ET_NEWSCENARIO_ID           1612
#define IDC_ET_NEWSCENARIO_DESC         1613
#define IDC_STATIC_INCIDENT             1614
#define IDC_ET_EVENTMESSAGE_INDICENT    1615
#define IDC_UD_EVENTMESSAGE_INDICENT    1616
#define IDC_STATIC_TITLE                1617
#define IDC_STATIC_MESSAGE              1618
#define IDC_TAB_MULTIPLAYER_EXPLORER    1619
#define IDC_STATIC_ADJUST               1620
#define IDC_CMB_ADJUST_THAT             1621
#define IDC_ET_FINDHERO                 1622
#define IDC_BT_FINDHERO                 1623
#define IDC_BT_TECHNOLOGY               1624
#define IDC_ET_EVENTMODIFYCITY_CITY     1624
#define IDC_ET_EVENTMODIFYCITY_SOLDIERS 1627
#define IDC_UD_EVENTMODIFYCITY_SOLDIERS 1628
#define IDC_LV_EVENTMODIFYSIDE_SIDE     1629
#define IDC_CMB_EVENTMODIFYSIDE_SIDE    1630
#define IDC_LV_EVENTMODIFYSIDE_AGREE    1631
#define IDC_LV_EVENTMODIFYCITY_SERVICE  1631
#define IDC_LV_EVENTMODIFYSIDE_TERMINATE 1632
#define IDC_CMB_EVENTMODIFYCITY_CITY    1632
#define IDC_LV_EVENTMODIFYSIDE_HERO     1633
#define IDC_ET_EVENTMODIFYSIDE_INCOME   1633
#define IDC_CMB_EVENTMODIFYSIDE_LEADER  1634
#define IDC_UD_EVENTMODIFYSIDE_INCOME   1635
#define IDC_LV_OBJECTIVES_WIN           1636
#define IDC_ET_EVENTMODIFYSIDE_GOLD     1636
#define IDC_ET_MSGID_MSGID              1637
#define IDC_LV_OBJECTIVES_WIN2          1637
#define IDC_LV_OBJECTIVES_LOSE          1637
#define IDC_UD_EVENTMODIFYSIDE_GOLD     1637
#define IDC_ET_MSGID_TRANSLATED         1638
#define IDC_ET_MSGID_MSGSTR             1638
#define IDC_CMB_EVENTMODIFYSIDE_CONTROLLER 1638
#define IDC_ET_TECHNOLOGY               1639
#define IDC_TV_FORMATION_EXPLORER       1642
#define IDC_LV_FACTIONEDIT_TOWERHERO    1643
#define IDC_STATIC_TOWERHERO            1644
#define IDC_STATIC_RED                  1645
#define IDC_LV_FEATURE_ATOM             1645
#define IDC_STATIC_GREEN                1646
#define IDC_LV_FEATUREEDIT_ITEMS        1646
#define IDC_STATIC_BLUE                 1647
#define IDC_LV_FEATUREEDIT_CANDIDATE    1647
#define IDC_LV_NOBLE_EXPLORER           1647
#define IDC_STATIC_RED4                 1647
#define IDC_ET_NOBLEEDIT_ID             1648
#define IDC_ET_NOBLEEDIT_IDSTATUS       1649
#define IDC_ET_NOBLEEDIT_NAME_MSGID     1650
#define IDC_ET_NOBLEEDIT_NAME           1651
#define IDC_CMB_NOBLEEDIT_LEVEL         1652
#define IDC_CHK_NOBLEEDIT_LEADER        1653
#define IDC_CHK_NOBLEEDIT_FORMATION     1654
#define IDC_STATIC_CONDITION            1655
#define IDC_STATIC_EFFECT               1656
#define IDC_ET_NOBLEEDIT_CITY           1657
#define IDC_UD_NOBLEEDIT_CITY           1658
#define IDC_ET_NOBLEEDIT_MERITORIOUS    1659
#define IDC_STATIC_OFFSET_X             1659
#define IDC_UD_NOBLEEDIT_MERITORIOUS    1660
#define IDC_STATIC_DEFINEDVARIABLES     1660
#define IDC_ET_NOBLEEDIT_LEADERSHIP     1661
#define IDC_STATIC_STATE                1661
#define IDC_UD_NOBLEEDIT_LEADERSHIP     1662
#define IDC_ET_PRELUDE_CFG              1662
#define IDC_ET_NOBLEEDIT_FORCE          1663
#define IDC_TV_BOOK_EXPLORER            1663
#define IDC_UD_NOBLEEDIT_FORCE          1664
#define IDC_ET_BOOK_TITLE_MSGID         1664
#define IDC_ET_NOBLEEDIT_INTELLECT      1665
#define IDC_ET_BOOK_TITLE               1665
#define IDC_UD_NOBLEEDIT_INTELLECT      1666
#define IDC_ET_BOOK_TEXTDOMAINSTATUS    1666
#define IDC_ET_NOBLEEDIT_POLITICS       1667
#define IDC_ET_BOOK_TEXTDOMAIN          1667
#define IDC_UD_NOBLEEDIT_POLITICS       1668
#define IDC_ET_TOPICEDIT_TITLE_MSGID    1668
#define IDC_ET_NOBLEEDIT_CHARM          1669
#define IDC_ET_TOPICEDIT_TITLE          1669
#define IDC_UD_NOBLEEDIT_CHARM          1670
#define IDC_ET_TOPICEDIT_ID             1670
#define IDC_ET_TOPICEDIT_TITLE_TEXTDOMAIN 1671
#define IDC_ET_TOPICEDIT_TITLE_TEXTDOMAINSTATUS 1672
#define IDC_ET_INTEGRATE_TEXT           1673
#define IDC_BT_INTEGRATE_CONVERT        1674
#define IDC_ET_CITYEDIT_ALIAS_MSGID     1675
#define IDC_ET_CITYEDIT_ALIAS           1676
#define IDM_RESET                       40009
#define IDM_HEROSTATE                   40010
#define IDM_UTYPE_GENERAL               40011
#define IDM_UTYPE_MTYPE                 40012
#define IDM_UTYPE_ATTACKI               40013
#define IDM_UTYPE_ATTACKII              40014
#define IDM_UTYPE_ATTACKIII             40015
#define IDM_SAVE                        40016
#define IDM_WGEN_DEL_CFGITEM            40017
#define IDM_SYS_SYNC                    40018
#define IDM_SYS_WGEN                    40019
#define IDM_SYS_CORE                    40021
#define IDM_SYS_PLAY                    40023
#define IDM_SYS_TBOX                    40025
#define IDM_SYS_BUILDER                 40027
#define IDM_REFRESH                     40029
#define IDM_SYNC_SYNC                   40031
#define IDM_SYNC_OPENPCDIR              40033
#define IDM_INTEGRATE                   40038
#define IDM_NEW                         40039
#define IDM_DOWNLOAD                    40041
#define IDM_UPLOAD                      40043
#define IDM_RENAME                      40044
#define IDM_DELETE                      40045
#define IDM_FIND                        40046
#define IDM_OK                          40047
#define IDM_CANCEL                      40048
#define IDM_OPEN                        40049
#define IDM_IMPORT                      40050
#define IDM_EXPORT                      40051
#define IDM_BACKUP                      40052
#define IDM_TECHNOLOGY_GENERAL          40053
#define IDM_EDIT                        40054
#define IDM_ADD                         40055
#define IDM_EXTRACT                     40056
#define IDM_TOSERVICE                   40060
#define IDM_TOWANDER                    40061
#define IDM_TORESERVE                   40062
#define IDM_TOMASTER                    40063
#define IDM_TOSECOND                    40064
#define IDM_TOTHIRD                     40065
#define IDM_TOSIDE                      40066
#define IDM_TOTOWER                     40067
#define IDM_EXPLORER_WML                40068
#define IDM_VARIABLE_ITEM0              40070
#define IDM_VARIABLE_ITEM1              40071
#define IDM_VARIABLE_ITEM2              40072
#define IDM_VARIABLE_ITEM3              40073
#define IDM_VARIABLE_ITEM4              40074
#define IDM_VARIABLE_ITEM5              40075
#define IDM_VARIABLE_ITEM6              40076
#define IDM_VARIABLE_ITEM7              40077
#define IDM_VARIABLE_ITEM8              40078
#define IDM_VARIABLE_ITEM9              40079
#define IDM_DELETE_ITEM0                40080
#define IDM_DELETE_ITEM1                40081
#define IDM_DELETE_ITEM2                40082
#define IDM_DELETE_ITEM3                40083
#define IDM_DELETE_ITEM4                40084
#define IDM_DELETE_ITEM5                40085
#define IDM_DELETE_ITEM6                40086
#define IDM_DELETE_ITEM7                40087
#define IDM_DELETE_ITEM8                40088
#define IDM_DELETE_ITEM9                40089
#define IDM_NEW_EXTRAINSDIST            40090
#define IDM_NEW_CAMPAIGN                40091
#define IDM_GENERATE_ITEM2              40092
#define IDM_GENERATE_ITEM3              40093
#define IDM_GENERATE_ITEM4              40094
#define IDM_GENERATE_ITEM5              40095
#define IDM_GENERATE_ITEM6              40096
#define IDM_TECHNOLOGY_ATOMIC           40097
#define IDM_TECHNOLOGY_COMPLEX          40098
#define IDM_TECHNOLOGY_STRATAGEM        40099
#define IDM_NEW_ITEM0                   40100
#define IDM_NEW_ITEM1                   40101
#define IDM_NEW_ITEM2                   40102
#define IDM_NEW_ITEM3                   40103
#define IDM_NEW_ITEM4                   40104
#define IDM_NEW_ITEM5                   40105
#define IDM_NEW_ITEM6                   40106
#define IDM_NEW_ITEM7                   40107
#define IDM_NEW_ITEM8                   40108
#define IDM_NEW_ITEM9                   40109
#define IDM_NEW_ITEM10                  40110
#define IDM_NEW_ITEM11                  40111
#define IDM_NEW_ITEM12                  40112
#define IDM_NEW_ITEM13                  40113
#define IDM_NEW_ITEM14                  40114
#define IDM_NEW_ITEM15                  40115
#define IDM_NEW_ITEM16                  40116
#define IDM_NEW_ITEM17                  40117
#define IDM_NEW_ITEM18                  40118
#define IDM_NEW_ITEM19                  40119
#define IDM_NEW_EVENT0                  40120
#define IDM_NEW_EVENT1                  40121
#define IDM_NEW_EVENT2                  40122
#define IDM_NEW_EVENT3                  40123
#define IDM_NEW_EVENT4                  40124
#define IDM_NEW_EVENT5                  40125
#define IDM_NEW_EVENT6                  40126
#define IDM_NEW_EVENT7                  40127
#define IDM_NEW_EVENT8                  40128
#define IDM_NEW_EVENT9                  40129
#define IDM_NEW_EVENT10                 40130
#define IDM_NEW_EVENT11                 40131
#define IDM_NEW_EVENT12                 40132
#define IDM_NEW_EVENT13                 40133
#define IDM_NEW_EVENT14                 40134
#define IDM_NEW_EVENT15                 40135
#define IDM_NEW_EVENT16                 40136
#define IDM_NEW_EVENT17                 40137
#define IDM_NEW_EVENT18                 40138
#define IDM_NEW_EVENT19                 40139
#define IDM_NEW_EVENT20                 40140
#define IDM_NEW_EVENT21                 40141
#define IDM_NEW_EVENT22                 40142
#define IDM_NEW_EVENT23                 40143
#define IDM_NEW_EVENT24                 40144
#define IDM_NEW_EVENT25                 40145
#define IDM_ADD_FRONT                   40146
#define IDM_ADD_BEHIND                  40147
#define IDM_ADD_SECTION                 40148
#define IDM_ADD_TOPIC                   40149
#define IDM_UP                          40150
#define IDM_DOWN                        40151
#define IDM_CONVERT_NORMAL              40152
#define IDM_CONVERT_POEDIT              40153
#define IDM_EXCHANGE                    40154
#define IDM_APPEND                      40155
#define IDM_NEW_EXTRAROSE               40156
#define IDM_MOD_RES0                    40160
#define IDM_MOD_RES1                    40161
#define IDM_MOD_RES2                    40162
#define IDM_MOD_RES3                    40163
#define IDM_MOD_RES4                    40164
#define IDM_MOD_PATCH0                  40165
#define IDM_MOD_PATCH1                  40166
#define IDM_MOD_PATCH2                  40167
#define IDM_MOD_PATCH3                  40168
#define IDM_MOD_PATCH4                  40169

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         40170
#define _APS_NEXT_CONTROL_VALUE         1677
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
