//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_WGEN                        101
#define IDD_ABOUT                       104
#define IDD_UTYPE                       105
#define IDD_CORE                        105
#define IDR_SYSMENU                     106
#define IDR_WGENMENU                    107
#define IDR_SYNCMENU                    108
#define IDR_XCHGMENU                    109
#define IDS_WGEN_RESET                  112
#define IDD_DDESC                       113
#define IDI_DEVICE                      115
#define IDD_TITLE                       116
#define IDI_DIR                         118
#define IDI_MP2                         119
#define IDI_MP4                         120
#define IDD_SYNC                        121
#define IDI_DOWNLOAD                    122
#define IDI_UPLOAD                      123
#define IDI_CHECK                       124
#define IDI_ICON2                       125
#define IDI_UNCHECK                     125
#define IDD_DIALOG1                     126
#define IDD_TBOX                        126
#define IDD_CAMPAIGN                    126
#define IDI_OPEN                        129
#define IDI_RESET                       131
#define IDI_SAVE                        132
#define IDI_XCHG                        133
#define IDI_REFRESH                     134
#define IDI_SYNC                        135
#define IDI_OPENPCDIR                   136
#define IDI_TITLE_XCHG                  137
#define IDI_TITLE_ABOUT                 138
#define IDI_TITLE_PLAY                  139
#define IDI_TITLE_SYNC                  140
#define IDI_TITLE_UPDATE                141
#define IDI_TITLE_WGEN                  142
#define IDB_CANCEL_UNSELECT             144
#define IDB_OK_SELECT                   145
#define IDB_OK_UNSELECT                 146
#define IDB_CANCEL_SELECT               147
#define IDD_HEROEDIT                    148
#define IDI_NEW                         154
#define IDI_ICON3                       155
#define IDI_DEL                         155
#define IDI_RENAME                      157
#define IDI_ICON4                       159
#define IDI_RENAME_DIS                  159
#define IDI_ICON5                       160
#define IDI_RESET_DIS                   160
#define IDI_ICON6                       161
#define IDI_SAVE_DIS                    161
#define IDI_ICON7                       162
#define IDI_DEL_DIS                     162
#define IDI_ICON8                       163
#define IDI_NEW_DIS                     163
#define IDI_ICON9                       164
#define IDI_OPEN_DIS                    164
#define IDI_XCHG_DIS                    165
#define IDI_OPENPCDIR_DIS               166
#define IDI_REFRESH_DIS                 167
#define IDI_SYNC_DIS                    168
#define IDI_TITLE_XCHG_DIS              169
#define IDI_TITLE_ABOUT_DIS             170
#define IDI_TITLE_PLAY_DIS              171
#define IDI_TITLE_SYNC_DIS              172
#define IDI_TITLE_UPDATE_DIS            173
#define IDI_TITLE_WGEN_DIS              174
#define IDI_INI                         176
#define IDI_TXT                         177
#define IDI_UNKNOWN                     178
#define IDI_CANCEL                      179
#define IDI_OK                          180
#define IDI_BACKUP                      183
#define IDI_ICON10                      184
#define IDI_BACKUP_DIS                  184
#define IDI_CF                          186
#define IDI_NETWORK                     187
#define IDB_REBOOT_UNSELECT             190
#define IDB_REBOOT_SELECT               191
#define IDB_REBOOT_UNSELECT_LIGHT       193
#define IDB_REBOOT_DISABLE              194
#define IDB_REFRESH_UNSELECT            196
#define IDB_WELCOME                     200
#define IDI_EDITOR                      201
#define IDD_VISUAL                      203
#define IDI_WITH_SYNC                   210
#define IDI_WITHOUT_SYNC                211
#define IDI_BUILD                       212
#define IDI_BUILD_DIS                   213
#define IDD_CAMPAIGN_MAIN               214
#define IDD_CAMPAIGN_SCENARIO           215
#define IDD_SIDEEDIT                    216
#define IDD_CITYEDIT                    217
#define IDD_TROOPEDIT                   218
#define IDD_FEATUREEDIT                 219
#define IDD_NEWCAMPAIGN                 220
#define IDD_UTYPEEDIT                   221
#define IDD_ATTACKEDIT                  222
#define IDD_MTYPEEDIT                   223
#define IDD_UTYPETROOP                  224
#define IDD_UTYPECITY                   225
#define IDD_UTYPEARTIFICAL              226
#define IDD_UTYPE2EDIT                  227
#define IDD_EVENTEDIT                   228
#define IDD_EVENTFILTER                 229
#define IDD_EVENTUNIT                   230
#define IDD_EVENTKILL                   231
#define IDD_CONDITION                   232
#define IDD_VARIABLE                    233
#define IDD_HAVEUNIT                    234
#define IDD_SETVARIABLE                 235
#define IDD_EVENTJOIN                   236
#define IDI_EVT_COMMAND                 237
#define IDI_EVT_FILTER                  238
#define IDI_EVT_EVENT                   239
#define IDI_EVT_CONDITION               240
#define IDI_EVT_IF                      241
#define IDI_EVT_THEN                    242
#define IDI_ICON1                       243
#define IDI_EVT_ATTRIBUTE               243
#define IDD_VISUAL2                     244
#define IDC_BT_WGEN_EDIT                1034
#define IDC_BT_XCHG_XCHG                1054
#define IDC_BT_XCHG_CANCELXCHG          1055
#define IDC_BT_ABOUT_HELP               1055
#define IDC_ST_ABOUT_PRODUCTNAME        1056
#define IDC_ST_ABOUT_CORPNAME           1058
#define IDC_ST_ABOUT_FWVERSION          1059
#define IDC_ST_ABOUT_HTTP               1060
#define IDC_CMB_WGEN_CFGDESC_SRC        1069
#define IDC_LV_DDESC_EXPLORER           1076
#define IDC_ET_DDESC_SUBAREA            1078
#define IDC_BT_DDESC_BROWSE             1080
#define IDC_LV_SYNC_EXPLORER            1081
#define IDC_LV_SYNC_SYNC                1082
#define IDC_UD_HEROEDIT_LEADERSHIP      1114
#define IDC_ET_CFGBEACON_CURRENTTIMEY   1115
#define IDC_CMB_HEROEDIT_GENDER         1115
#define IDC_UD_CFGBEACON_BESTTIMEX      1116
#define IDC_ET_HEROEDIT_LEADERSHIP      1116
#define IDC_ET_CFGBEACON_BESTTIMEX      1117
#define IDC_CMB_CFGSYS_VIDEO_SOURCE     1117
#define IDC_CMB_HEROEDIT_CONSORT        1117
#define IDC_UD_CFGBEACON_BESTTIMEY      1118
#define IDC_CMB_HEROEDIT_OATH0          1118
#define IDC_ET_CFGBEACON_BESTTIMEY      1119
#define IDC_ET_SYNC_SUBAREA             1119
#define IDC_CMB_HEROEDIT_OATH1          1119
#define IDC_ET_SYNC_WORKDIR             1120
#define IDC_CMB_HEROEDIT_AMBITION       1120
#define IDC_ET_HEROEDIT_CATALOG         1121
#define IDC_UD_HEROEDIT_CATALOG         1122
#define IDC_BT_WGEN_REBOOT              1123
#define IDC_ET_HEROEDIT_IMAGE           1123
#define IDC_UD_HEROEDIT_IMAGE           1124
#define IDC_ET_HEROEDIT_LEADERSHIPXP    1125
#define IDC_CHK_UPDATE_AUTOSAVE         1126
#define IDC_UD_HEROEDIT_LEADERSHIPXP    1126
#define IDC_CMB_HEROEDIT_PARENT0        1127
#define IDC_CMB_HEROEDIT_PARENT1        1128
#define IDC_CMB_HEROEDIT_FEATURE        1129
#define IDC_ET_HEROEDIT_ARMS0XP         1130
#define IDC_UD_HEROEDIT_ARMS0XP         1131
#define IDC_CMB_HEROEDIT_ARMS0          1132
#define IDC_ET_HEROEDIT_BIOGRAPHY       1133
#define IDC_CMB_HEROEDIT_ARMS1          1134
#define IDC_CMB_HEROEDIT_ARMS2          1135
#define IDC_CMB_HEROEDIT_INTIMATE0      1136
#define IDC_CMB_HEROEDIT_ARMS3          1137
#define IDC_CMB_HEROEDIT_ARMS4          1138
#define IDC_CMB_HEROEDIT_INTIMATE1      1139
#define IDC_CMB_HEROEDIT_INTIMATE2      1140
#define IDC_CMB_HEROEDIT_HATE0          1141
#define IDC_CMB_HEROEDIT_HATE1          1142
#define IDC_CMB_HEROEDIT_HATE2          1143
#define IDC_CMB_HEROEDIT_FEATURE2       1144
#define IDC_CMB_HEROEDIT_SIDEFEATURE    1144
#define IDC_ET_HEROEDIT_HEART           1145
#define IDC_ET_HEROEDIT_NAME            1146
#define IDC_UD_HEROEDIT_HEART           1147
#define IDC_ET_HEROEDIT_NUMBER          1148
#define IDC_ET_HEROEDIT_SKILL0XP        1149
#define IDC_UD_HEROEDIT_SKILL0XP        1150
#define IDC_ET_HEROEDIT_INTELLECT       1151
#define IDC_UD_HEROEDIT_INTELLECT       1152
#define IDC_ET_HEROEDIT_FORCE           1153
#define IDC_ST_WELCOME                  1154
#define IDC_UD_HEROEDIT_FORCE           1154
#define IDC_ST_MEDIA                    1155
#define IDC_ET_HEROEDIT_POLITICS        1155
#define IDC_ST_SYNC_BLANK               1156
#define IDC_UD_HEROEDIT_POLITICS        1156
#define IDC_ET_HEROEDIT_CHARM           1157
#define IDC_UD_HEROEDIT_INTELLECT3      1158
#define IDC_UD_HEROEDIT_CHARM           1158
#define IDC_ET_HEROEDIT_FORCEXP         1159
#define IDC_UD_HEROEDIT_FORCEXP         1160
#define IDC_ET_HEROEDIT_INTELLECTXP     1161
#define IDC_UD_HEROEDIT_INTELLECTXP     1162
#define IDC_ET_HEROEDIT_POLITICSXP      1163
#define IDC_UD_HEROEDIT_POLITICSXP      1164
#define IDC_ET_HEROEDIT_CHARMXP         1165
#define IDC_UD_HEROEDIT_CHARM2          1166
#define IDC_UD_HEROEDIT_CHARMXP         1166
#define IDC_ET_HEROEDIT_ARMS1XP         1167
#define IDC_UD_HEROEDIT_ARMS1XP         1168
#define IDC_ET_HEROEDIT_ARMS2XP         1169
#define IDC_UD_HEROEDIT_ARMS2XP         1170
#define IDC_ET_HEROEDIT_ARMS3XP         1171
#define IDC_ET_DDESC_WWWROOT            1172
#define IDC_UD_HEROEDIT_ARMS3XP         1172
#define IDC_ET_HEROEDIT_ARMS4XP         1173
#define IDC_UD_HEROEDIT_ARMS4XP         1174
#define IDC_ET_HEROEDIT_SKILL2XP        1175
#define IDC_UD_HEROEDIT_SKILL2XP        1176
#define IDC_ET_HEROEDIT_SKILL3XP        1177
#define IDC_UD_HEROEDIT_SKILL3XP        1178
#define IDC_CMB_HEROEDIT_SKILL0         1179
#define IDC_CMB_HEROEDIT_SKILL1         1180
#define IDC_CMB_HEROEDIT_SKILL2         1181
#define IDC_CMB_HEROEDIT_SKILL3         1182
#define IDC_CMB_HEROEDIT_TREASURE0      1183
#define IDC_ET_HEROEDIT_SKILL1XP        1184
#define IDC_UD_HEROEDIT_SKILL1XP        1185
#define IDC_LV_TBOX_DESC                1204
#define IDC_LV_WGEN_EDITOR              1204
#define IDC_TV_DDESC_EXPLORER           1206
#define IDC_TV_CFG_EXPLORER             1212
#define IDC_ET_WGEN_FIND                1213
#define IDC_TV_CORE_EXPLORER            1214
#define IDC_TAB_CAMP_SCENARIO           1215
#define IDC_ET_CAMPMAIN_ID              1217
#define IDC_ET_CAMPMAIN_FILE            1218
#define IDC_ET_CAMPMAIN_NAME            1219
#define IDC_ET_CAMPMAIN_ABBREV_MSGID    1220
#define IDC_ET_CAMPMAIN_ICON            1221
#define IDC_BT_CAMPMAIN_BROWSEICON      1222
#define IDC_ET_CAMPMAIN_IMAGE           1223
#define IDC_BT_CAMPMAIN_BROWSEIMAGE     1224
#define IDC_ET_CAMPMAIN_DESC            1225
#define IDC_CHK_CAMPMAIN_RPGMODE        1226
#define IDC_ET_CAMPMAIN_ABBREV          1227
#define IDC_ET_CAMPMAIN_TEXTDOMAIN      1228
#define IDC_CMB_CAMPMAIN_RANK           1229
#define IDC_ET_CAMPMAIN_FIRSTSCENARIO   1230
#define IDC_ET_CAMPSCENARIO_FILE        1230
#define IDC_ET_CAMPMAIN_NAME_MSGID      1230
#define IDC_ET_CAMPSCENARIO_ID          1231
#define IDC_ET_CAMPMAIN_DESC_MSGID      1231
#define IDC_ET_CAMPSCENARIO_IDSTATUS    1232
#define IDC_ET_CAMPMAIN_TEXTDOMAINSTATUS 1232
#define IDC_ET_CAMPSCENARIO_TURNS       1233
#define IDC_ET_CAMPSCENARIO_MAP         1234
#define IDC_ET_CAMPSCENARIO_MDACTIVITY  1235
#define IDC_ET_CAMPSCENARIO_WIN         1236
#define IDC_UD_CAMPSCENARIO_TURNS       1237
#define IDC_UD_CAMPSCENARIO_MDACTIVITY  1238
#define IDC_ET_CAMPSCENARIO_LOSE        1239
#define IDC_LV_CAMPSCENARIO_SIDE        1240
#define IDC_BT_CAMPSCENARIO_BROWSEMAP   1241
#define IDC_ET_SIDEEDIT_SIDE            1242
#define IDC_ET_CAMPSCENARIO_WIN_MSGID   1242
#define IDC_ET_SIDEEDIT_NAME            1243
#define IDC_ET_CAMPSCENARIO_LOSE_MSGID  1243
#define IDC_CHK_SIDEEDIT_SHROUD         1244
#define IDC_CHK_SIDEEDIT_CONTROLLER     1244
#define IDC_ET_CAMPSCENARIO_NAME        1244
#define IDC_CHK_SIDEEDIT_FOG            1245
#define IDC_ET_SIDEEDIT_NAME2           1245
#define IDC_ET_SIDEEDIT_NAME_MSGID      1245
#define IDC_ET_CAMPSCENARIO_NAME_MSGID  1245
#define IDC_CMB_SIDEEDIT_LEADER         1246
#define IDC_LV_CAMPSCENARIO_EVENT       1246
#define IDC_ET_SIDEEDIT_GOLD            1247
#define IDC_ET_SIDEEDIT_INCOME          1248
#define IDC_ET_SIDEEDIT_NAVIGATIONXP    1249
#define IDC_CMB_SIDEEDIT_NAVIGATION     1250
#define IDC_BT_SIDEEDIT_ADDCITY         1251
#define IDC_BT_SIDEEDIT_DELETECITY      1252
#define IDC_CMB_SIDEEDIT_CITYTYPE       1253
#define IDC_CMB_SIDEEDIT_CITYHERO       1254
#define IDC_ET_SIDEEDIT_CITYX           1255
#define IDC_ET_SIDEEDIT_CITYY           1256
#define IDC_LV_SIDEEDIT_TROOP           1257
#define IDC_UD_SIDEEDIT_CITYX           1258
#define IDC_UD_SIDEEDIT_CITYY           1259
#define IDC_LV_SIDEEDIT_CITY2           1260
#define IDC_LV_SIDEEDIT_CITY            1260
#define IDC_CMB_CITYEDIT_HERO           1260
#define IDC_CMB_CITYEDIT_TYPE           1261
#define IDC_LV_SIDEEDIT_FEATURE         1261
#define IDC_ET_CITYEDIT_X               1262
#define IDC_LV_SIDEEDIT_FEATURE2        1262
#define IDC_LV_SIDEEDIT_BUILD           1262
#define IDC_ET_CITYEDIT_Y               1263
#define IDC_UD_CITYEDIT_X               1264
#define IDC_UD_CITYEDIT_Y               1265
#define IDC_UD_SIDEEDIT_INCOME          1265
#define IDC_LV_CITYEDIT_TRAITS          1266
#define IDC_LV_CITYEDIT_TRAIT           1266
#define IDC_UD_SIDEEDIT_NAVIGATIONXP    1266
#define IDC_LV_CITYEDIT_SERVICE         1267
#define IDC_LV_CITYEDIT_SERVICE2        1268
#define IDC_LV_CITYEDIT_WANDER          1268
#define IDC_CMB_CITYEDIT_MAYOR          1269
#define IDC_ET_CITYEDIT_EAX             1270
#define IDC_ET_CITYEDIT_EAY             1271
#define IDC_UD_CITYEDIT_EAX             1272
#define IDC_UD_CITYEDIT_EAY             1273
#define IDC_LV_CITYEDIT_EA              1274
#define IDC_BT_CITYEDIT_ADDEA           1275
#define IDC_LV_CITYEDIT_CANDIDATE       1276
#define IDC_LV_CITYEDIT_NOTRECRUIT      1277
#define IDC_CMB_CITYEDIT_CHARACTER      1278
#define IDC_CMB_TROOPEDIT_TYPE          1279
#define IDC_ET_TROOPEDIT_X              1280
#define IDC_UD_TROOPEDIT_X              1281
#define IDC_ET_TROOPEDIT_Y              1282
#define IDC_UD_TROOPEDIT_Y              1283
#define IDC_LV_TROOPEDIT_CANDIDATE      1284
#define IDC_LV_TROOPEDIT_HERO           1285
#define IDC_CMB_TROOPEDIT_CITY          1286
#define IDC_LV_TROOPEDIT_TRAIT          1287
#define IDC_CMB_FEATUREEDIT_ARMS        1288
#define IDC_CMB_TROOPEDIT_CHARACTER     1288
#define IDC_CMB_FEATUREEDIT_LEVEL       1289
#define IDC_UD_SIDEEDIT_GOLD            1289
#define IDC_CMB_FEATUREEDIT_FEATURE     1290
#define IDC_ET_NEWCAMP_ID               1290
#define IDC_ET_NEWCAMP_FIRSTSCENARIOID  1291
#define IDC_COMBO1                      1291
#define IDC_CMB_CAMPSCENARIO_NEXTSCENARIO 1291
#define IDC_CMB_UTYPEEDIT_TYPE          1291
#define IDC_CMB_MTYPEEDIT_TYPE          1291
#define IDC_CMB_UTYPEARTIFICAL_MASTER   1291
#define IDC_CMB_EVENTFILTER_MASTERHERO  1291
#define IDC_CMB_EVENTUNIT_              1291
#define IDC_CMB_EVENTUNIT_TYPE          1291
#define IDC_CMB_CONDITION_TYPE          1291
#define IDC_CMB_VARIABLE_OP             1291
#define IDC_ET_NEWCAMP_DESC             1292
#define IDC_CMB_CAMPMAIN_FIRSTSCENARIO  1292
#define IDC_CMB_UTYPEEDIT_LEVEL         1292
#define IDC_CMB_ATTACKEDIT_RANGE        1292
#define IDC_CMB_UTYPEARTIFICAL_GUARD    1292
#define IDC_CMB_EVENTUNIT_CITY          1292
#define IDC_CMB_EVENTFILTER_CITY        1292
#define IDC_ET_UTYPEEDIT_FILE           1293
#define IDC_CMB_ATTACKEDIT_TYPE         1293
#define IDC_CMB_EVENTUNIT_SIDE          1293
#define IDC_ET_NEWCAMP_FIRSTSCENARIODESC 1294
#define IDC_ET_UTYPEEDIT_ID             1294
#define IDC_ET_UTYPEEDIT_IDSTATUS       1295
#define IDC_LV_UTYPEEDIT_ADVANCESTO     1296
#define IDC_ET_UTYPEEDIT_NAME_MSGID     1297
#define IDC_ET_UTYPEEDIT_NAME           1298
#define IDC_ET_UTYPEEDIT_RACE           1299
#define IDC_LV_UTYPEEDIT_ABILITIES      1300
#define IDC_ET_UTYPEEDIT_HP             1301
#define IDC_UD_UTYPEEDIT_HP             1302
#define IDC_ET_UTYPEEDIT_XP             1303
#define IDC_ET_ATTACKEDIT_TEXTDOMAIN    1303
#define IDC_UD_UTYPEEDIT_XP             1304
#define IDC_ET_ATTACKEDIT_ID            1304
#define IDC_ET_ATTACKEDIT_IDSTATUS      1305
#define IDC_ET_ATTACKEDIT_NAME_MSGID    1306
#define IDC_CMB_UTYPEEDIT_ALIGNMENT     1307
#define IDC_ET_ATTACKEDIT_NAME          1307
#define IDC_ET_UTYPEEDIT_COST           1308
#define IDC_LV_ATTACKEDIT_SPECIALS      1308
#define IDC_UD_UTYPEEDIT_COST           1309
#define IDC_ET_ATTACKEDIT_DAMAGE        1309
#define IDC_LV_UTYPEEDIT_ATTACK         1310
#define IDC_UD_ATTACKEDIT_DAMAGE        1310
#define IDC_ET_UTYPEEDIT_DESC_MSGID     1311
#define IDC_ET_ATTACKEDIT_NUMBER        1311
#define IDC_ET_UTYPEEDIT_DESC           1312
#define IDC_UD_ATTACKEDIT_NUMBER        1312
#define IDC_ET_UTYPEEDIT_TEXTDOMAIN     1313
#define IDC_ET_ATTACKEDIT_ICON          1313
#define IDC_ET_UTYPEEDIT_TEXTDOMAINSTATUS 1314
#define IDC_BT_ATTACKEDIT_BROWSEICON    1314
#define IDC_CMB_UTYPEEDIT_ARMS          1315
#define IDC_LV_UTYPEEDIT_MTYPE          1316
#define IDC_ET_UTYPEEDIT_TYPE           1317
#define IDC_LV_MTYPEEDIT_RESISTANCE     1318
#define IDC_ET_MTYPEEDIT_NAME           1319
#define IDC_ET_MTYPEEDIT_VALUE          1320
#define IDC_UD_MTYPEEDIT_VALUE          1321
#define IDC_CHK_UTYPEEDIT_ZOC           1322
#define IDC_LV_MTYPEEDIT_DEFENSE        1322
#define IDC_LV_MTYPEEDIT_MOVEMENTCOSTS  1323
#define IDC_STATIC_UTYPEEDIT_ABILITIES  1324
#define IDC_STATIC_UTYPEEDIT_ADVANCESTO 1325
#define IDC_STATIC_ATTACKEDIT_SPECIALS  1325
#define IDC_ET_UTYPETROOP_MOVEMENT      1326
#define IDC_CMB_UTYPETROOP_CHARACTER    1327
#define IDC_UD_UTYPETROOP_MOVEMENT      1328
#define IDC_CHK_UTYPETROOP_LANDWALL     1329
#define IDC_BT_UTYPEEDIT_SPECIAL        1330
#define IDC_CHK_UTYPETROOP_LEADER       1330
#define IDC_ET_UTYPECITY_TURNEXPERIENCE 1331
#define IDC_UD_UTYPECITY_TURNEXPERIENCE 1332
#define IDC_ET_UTYPEARTIFICAL_HEAL      1333
#define IDC_ET_UTYPECITY_HEAL           1333
#define IDC_UD_UTYPEARTIFICAL_HEAL      1334
#define IDC_UD_UTYPECITY_HEAL           1334
#define IDC_ET_UTYPEARTIFICAL_INCOME    1335
#define IDC_ET_UTYPEEDIT_MELEEINCREASE  1335
#define IDC_UD_UTYPEARTIFICAL_INCOME    1336
#define IDC_UD_UTYPEEDIT_MELEEINCREASE  1336
#define IDC_ET_UTYPEEDIT_RANGEDINCREASE 1337
#define IDC_STATIC_CITYEDIT_NOTRECRUIT  1337
#define IDC_UD_UTYPEEDIT_RANGEDINCREASE 1338
#define IDC_TV_EVENTEDIT_EXPLORER       1338
#define IDC_ET_UTYPEEDIT_CASTINCREASE   1339
#define IDC_LV_EVENTFILTER_MUSTHEROS    1339
#define IDC_UD_UTYPEEDIT_CASTINCREASE   1340
#define IDC_STATIC_EVENTFILTER_MUSTHEROS 1340
#define IDC_LV_EVENTUNIT_HEROSARMY      1341
#define IDC_STATIC_EVENTUNIT_HEROSARMY  1342
#define IDC_LV_EVENTUNIT_VARIABLE       1343
#define IDC_LV_EVENT_VARIABLE           1343
#define IDC_EDIT1                       1344
#define IDC_ET_EVENTUNIT_HEROSARMY      1344
#define IDC_ET_VARIABLE_LEFT            1344
#define IDC_ET_HAVEUNIT_FILTER          1344
#define IDC_ET_EVENTUNIT_TYPE           1345
#define IDC_ET_VARIABLE_RIGHT           1345
#define IDC_ET_EVENTUNIT_CITY           1346
#define IDC_ET_EVENTUNIT_SIDE           1347
#define IDC_ET_EVENTUNIT_X              1348
#define IDC_UD_EVENTUNIT_X              1349
#define IDC_ET_EVENTUNIT_Y              1350
#define IDC_UD_EVENTUNIT_Y              1351
#define IDC_ET_EVENTUNIT_VARX           1352
#define IDC_CMB_EVENTKILL_MASTERHERO    1352
#define IDC_ET_EVENTUNIT_VARY           1353
#define IDC_ET_EVENTKILL_MASTERHERO     1353
#define IDC_LV_EVENTKILL_VARIABLE       1354
#define IDC_STATIC_EVENTUNIT_HEROSARMY2 1354
#define IDC_STATIC_EVENTUNIT_HEROSARMY3 1355
#define IDC_TAB_CONDITION_CONDITION     1356
#define IDC_CMB_EVENTJOIN_JOIN          1356
#define IDC_ET_EVENTJOIN_JOIN           1357
#define IDC_BT_HAVEUNIT_FILTER          1358
#define IDC_LV_VARIABLE_ENV             1359
#define IDC_ET_SETVARIABLE_NAME         1360
#define IDC_CMB_SETVARIABLE_OP          1361
#define IDC_ET_SETVARIABLE_VALUE        1362
#define IDC_LV_SETVARIABLE_ENV          1363
#define IDC_ET_SETVARIABLE_NAMESTATUS   1364
#define IDC_ET_EVENTJOIN_MASTERHERO     1364
#define IDC_CMB_EVENTJOIN_MASTERHERO    1365
#define IDC_LV_EVENTJOIN_VARIABLE       1366
#define IDC_LIST1                       1367
#define IDC_LV_VISUAL2_EXPLORER         1367
#define IDM_RESET                       40009
#define IDM_UTYPE                       40010
#define IDM_UTYPE_GENERAL               40011
#define IDM_UTYPE_MTYPE                 40012
#define IDM_UTYPE_ATTACKI               40013
#define IDM_UTYPE_ATTACKII              40014
#define IDM_UTYPE_ATTACKIII             40015
#define IDM_SAVE                        40016
#define IDM_WGEN_DEL_CFGITEM            40017
#define IDM_SYS_SYNC                    40018
#define IDM_SYS_WGEN                    40019
#define IDM_SYS_XCHG                    40021
#define IDM_SYS_PLAY                    40023
#define IDM_SYS_TBOX                    40025
#define IDM_SYS_ABOUT                   40027
#define IDM_REFRESH                     40029
#define IDM_SYNC_SYNC                   40031
#define IDM_SYNC_OPENPCDIR              40033
#define IDM_XCHG_OPEN                   40035
#define IDM_XCHG_XCHG                   40037
#define IDM_NEW                         40039
#define IDM_DOWNLOAD                    40041
#define IDM_UPLOAD                      40043
#define IDM_DELETE                      40045
#define IDM_FIND                        40046
#define IDM_OK                          40047
#define IDM_CANCEL                      40048
#define IDM_OPEN                        40049
#define IDM_IMPORT                      40050
#define IDM_EXPORT                      40051
#define IDM_BACKUP                      40052
#define IDM_FMTSETTING                  40053
#define IDM_EDIT                        40054
#define IDM_ADD                         40055
#define IDM_EXTRACT                     40056
#define IDM_TOSERVICE                   40060
#define IDM_TOWANDER                    40061
#define IDM_TOMASTER                    40062
#define IDM_TOSECOND                    40063
#define IDM_TOTHIRD                     40064
#define IDM_EXPLORER_WML                40065
#define IDM_VARIABLE_ITEM0              40070
#define IDM_VARIABLE_ITEM1              40071
#define IDM_VARIABLE_ITEM2              40072
#define IDM_VARIABLE_ITEM3              40073
#define IDM_VARIABLE_ITEM4              40074
#define IDM_VARIABLE_ITEM5              40075
#define IDM_VARIABLE_ITEM6              40076
#define IDM_VARIABLE_ITEM7              40077
#define IDM_VARIABLE_ITEM8              40078
#define IDM_VARIABLE_ITEM9              40079
#define IDM_DELETE_ITEM0                40080
#define IDM_DELETE_ITEM1                40081
#define IDM_DELETE_ITEM2                40082
#define IDM_DELETE_ITEM3                40083
#define IDM_DELETE_ITEM4                40084
#define IDM_DELETE_ITEM5                40085
#define IDM_DELETE_ITEM6                40086
#define IDM_DELETE_ITEM7                40087
#define IDM_DELETE_ITEM8                40088
#define IDM_DELETE_ITEM9                40089
#define IDM_NEW_EXTRAINSDIST            40090
#define IDM_NEW_CAMPAIGN                40091
#define IDM_GENERATE_ITEM2              40092
#define IDM_GENERATE_ITEM3              40093
#define IDM_GENERATE_ITEM4              40094
#define IDM_GENERATE_ITEM5              40095
#define IDM_GENERATE_ITEM6              40096
#define IDM_GENERATE_ITEM7              40097
#define IDM_GENERATE_ITEM8              40098
#define IDM_GENERATE_ITEM9              40099
#define IDM_NEW_ITEM0                   40100
#define IDM_NEW_ITEM1                   40101
#define IDM_NEW_ITEM2                   40102
#define IDM_NEW_ITEM3                   40103
#define IDM_NEW_ITEM4                   40104
#define IDM_NEW_ITEM5                   40105
#define IDM_NEW_ITEM6                   40106
#define IDM_NEW_ITEM7                   40107
#define IDM_NEW_ITEM8                   40108
#define IDM_NEW_ITEM9                   40109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         40100
#define _APS_NEXT_CONTROL_VALUE         1368
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
