//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_WGEN                        101
#define IDD_ABOUT                       104
#define IDD_TB                          105
#define IDR_SYSMENU                     106
#define IDR_WGENMENU                    107
#define IDR_SYNCMENU                    108
#define IDR_XCHGMENU                    109
#define IDS_WGEN_RESET                  112
#define IDD_DDESC                       113
#define IDI_DEVICE                      115
#define IDD_TITLE                       116
#define IDI_DIR                         118
#define IDI_MP2                         119
#define IDI_MP4                         120
#define IDD_SYNC                        121
#define IDI_DOWNLOAD                    122
#define IDI_UPLOAD                      123
#define IDI_CHECK                       124
#define IDI_ICON2                       125
#define IDI_UNCHECK                     125
#define IDD_DIALOG1                     126
#define IDD_TBOX                        126
#define IDI_OPEN                        129
#define IDI_RESET                       131
#define IDI_SAVE                        132
#define IDI_XCHG                        133
#define IDI_REFRESH                     134
#define IDI_SYNC                        135
#define IDI_OPENPCDIR                   136
#define IDI_TITLE_XCHG                  137
#define IDI_TITLE_ABOUT                 138
#define IDI_TITLE_PLAY                  139
#define IDI_TITLE_SYNC                  140
#define IDI_TITLE_UPDATE                141
#define IDI_TITLE_WGEN                  142
#define IDB_CANCEL_UNSELECT             144
#define IDB_OK_SELECT                   145
#define IDB_OK_UNSELECT                 146
#define IDB_CANCEL_SELECT               147
#define IDD_HEROEDIT                    148
#define IDI_NEW                         154
#define IDI_ICON3                       155
#define IDI_DEL                         155
#define IDI_RENAME                      157
#define IDI_ICON4                       159
#define IDI_RENAME_DIS                  159
#define IDI_ICON5                       160
#define IDI_RESET_DIS                   160
#define IDI_ICON6                       161
#define IDI_SAVE_DIS                    161
#define IDI_ICON7                       162
#define IDI_DEL_DIS                     162
#define IDI_ICON8                       163
#define IDI_NEW_DIS                     163
#define IDI_ICON9                       164
#define IDI_OPEN_DIS                    164
#define IDI_XCHG_DIS                    165
#define IDI_OPENPCDIR_DIS               166
#define IDI_REFRESH_DIS                 167
#define IDI_SYNC_DIS                    168
#define IDI_TITLE_XCHG_DIS              169
#define IDI_TITLE_ABOUT_DIS             170
#define IDI_TITLE_PLAY_DIS              171
#define IDI_TITLE_SYNC_DIS              172
#define IDI_TITLE_UPDATE_DIS            173
#define IDI_TITLE_WGEN_DIS              174
#define IDI_INI                         176
#define IDI_TXT                         177
#define IDI_UNKNOWN                     178
#define IDI_CANCEL                      179
#define IDI_OK                          180
#define IDI_BACKUP                      183
#define IDI_ICON10                      184
#define IDI_BACKUP_DIS                  184
#define IDI_CF                          186
#define IDI_NETWORK                     187
#define IDB_BITMAP2                     189
#define IDB_REBOOT_UNSELECT             190
#define IDB_REBOOT_SELECT               191
#define IDB_REBOOT_UNSELECT_LIGHT       193
#define IDB_REBOOT_DISABLE              194
#define IDB_REFRESH_UNSELECT            196
#define IDB_WELCOME                     200
#define IDI_EDITOR                      201
#define IDD_CFG                         203
#define IDI_WITH_SYNC                   210
#define IDI_WITHOUT_SYNC                211
#define IDI_BUILD                       212
#define IDI_BUILD_DIS                   213
#define IDC_BT_WGEN_EDIT                1034
#define IDC_BT_XCHG_XCHG                1054
#define IDC_BT_XCHG_CANCELXCHG          1055
#define IDC_BT_ABOUT_HELP               1055
#define IDC_ST_ABOUT_PRODUCTNAME        1056
#define IDC_ST_ABOUT_CORPNAME           1058
#define IDC_ST_ABOUT_FWVERSION          1059
#define IDC_ST_ABOUT_HTTP               1060
#define IDC_CMB_WGEN_CFGDESC_SRC        1069
#define IDC_LV_DDESC_EXPLORER           1076
#define IDC_ET_DDESC_SUBAREA            1078
#define IDC_BT_DDESC_BROWSE             1080
#define IDC_LV_SYNC_EXPLORER            1081
#define IDC_LV_SYNC_SYNC                1082
#define IDC_UD_HEROEDIT_LEADERSHIP      1114
#define IDC_ET_CFGBEACON_CURRENTTIMEY   1115
#define IDC_CMB_HEROEDIT_GENDER         1115
#define IDC_UD_CFGBEACON_BESTTIMEX      1116
#define IDC_ET_HEROEDIT_LEADERSHIP      1116
#define IDC_ET_CFGBEACON_BESTTIMEX      1117
#define IDC_CMB_CFGSYS_VIDEO_SOURCE     1117
#define IDC_CMB_HEROEDIT_CONSORT        1117
#define IDC_UD_CFGBEACON_BESTTIMEY      1118
#define IDC_CMB_HEROEDIT_OATH0          1118
#define IDC_ET_CFGBEACON_BESTTIMEY      1119
#define IDC_ET_SYNC_SUBAREA             1119
#define IDC_CMB_HEROEDIT_OATH1          1119
#define IDC_ET_SYNC_WORKDIR             1120
#define IDC_CMB_HEROEDIT_AMBITION       1120
#define IDC_ET_HEROEDIT_CATALOG         1121
#define IDC_UD_HEROEDIT_CATALOG         1122
#define IDC_BT_WGEN_REBOOT              1123
#define IDC_ET_HEROEDIT_IMAGE           1123
#define IDC_UD_HEROEDIT_IMAGE           1124
#define IDC_ET_HEROEDIT_LEADERSHIPXP    1125
#define IDC_CHK_UPDATE_AUTOSAVE         1126
#define IDC_UD_HEROEDIT_LEADERSHIPXP    1126
#define IDC_CMB_HEROEDIT_PARENT0        1127
#define IDC_CMB_HEROEDIT_PARENT1        1128
#define IDC_CMB_HEROEDIT_FEATURE        1129
#define IDC_ET_HEROEDIT_ARMS0XP         1130
#define IDC_UD_HEROEDIT_ARMS0XP         1131
#define IDC_CMB_HEROEDIT_ARMS0          1132
#define IDC_ET_HEROEDIT_BIOGRAPHY       1133
#define IDC_CMB_HEROEDIT_ARMS1          1134
#define IDC_CMB_HEROEDIT_ARMS2          1135
#define IDC_CMB_HEROEDIT_INTIMATE0      1136
#define IDC_CMB_HEROEDIT_ARMS3          1137
#define IDC_CMB_HEROEDIT_ARMS4          1138
#define IDC_CMB_HEROEDIT_INTIMATE1      1139
#define IDC_CMB_HEROEDIT_INTIMATE2      1140
#define IDC_CMB_HEROEDIT_HATE0          1141
#define IDC_CMB_HEROEDIT_HATE1          1142
#define IDC_CMB_HEROEDIT_HATE2          1143
#define IDC_CMB_HEROEDIT_FEATURE2       1144
#define IDC_CMB_HEROEDIT_SIDEFEATURE    1144
#define IDC_ET_HEROEDIT_HEART           1145
#define IDC_ET_HEROEDIT_NAME            1146
#define IDC_UD_HEROEDIT_HEART           1147
#define IDC_ET_HEROEDIT_NUMBER          1148
#define IDC_ET_HEROEDIT_SKILL0XP        1149
#define IDC_UD_HEROEDIT_SKILL0XP        1150
#define IDC_ET_HEROEDIT_INTELLECT       1151
#define IDC_UD_HEROEDIT_INTELLECT       1152
#define IDC_ET_HEROEDIT_FORCE           1153
#define IDC_ST_WELCOME                  1154
#define IDC_UD_HEROEDIT_FORCE           1154
#define IDC_ST_MEDIA                    1155
#define IDC_ET_HEROEDIT_POLITICS        1155
#define IDC_ST_SYNC_BLANK               1156
#define IDC_UD_HEROEDIT_POLITICS        1156
#define IDC_ET_HEROEDIT_CHARM           1157
#define IDC_UD_HEROEDIT_INTELLECT3      1158
#define IDC_UD_HEROEDIT_CHARM           1158
#define IDC_ET_HEROEDIT_FORCEXP         1159
#define IDC_UD_HEROEDIT_FORCEXP         1160
#define IDC_ET_HEROEDIT_INTELLECTXP     1161
#define IDC_UD_HEROEDIT_INTELLECTXP     1162
#define IDC_ET_HEROEDIT_POLITICSXP      1163
#define IDC_UD_HEROEDIT_POLITICSXP      1164
#define IDC_ET_HEROEDIT_CHARMXP         1165
#define IDC_UD_HEROEDIT_CHARM2          1166
#define IDC_UD_HEROEDIT_CHARMXP         1166
#define IDC_ET_HEROEDIT_ARMS1XP         1167
#define IDC_UD_HEROEDIT_ARMS1XP         1168
#define IDC_ET_HEROEDIT_ARMS2XP         1169
#define IDC_UD_HEROEDIT_ARMS2XP         1170
#define IDC_ET_HEROEDIT_ARMS3XP         1171
#define IDC_ET_DDESC_DVR                1172
#define IDC_ET_CFGOSD_TSX               1172
#define IDC_ET_DDESC_WWWROOT            1172
#define IDC_UD_HEROEDIT_ARMS3XP         1172
#define IDC_ST_UPDATE_HWNAME            1173
#define IDC_ET_CFGOSD_TSY               1173
#define IDC_ET_HEROEDIT_ARMS4XP         1173
#define IDC_GRP_UPDATE_IP               1174
#define IDC_UD_HEROEDIT_ARMS4XP         1174
#define IDC_GRP_UPDATE_STATIC           1175
#define IDC_ET_HEROEDIT_SKILL1XP        1175
#define IDC_ST_UPDATE_IPADDR            1176
#define IDC_UD_HEROEDIT_SKILL1XP        1176
#define IDC_ST_UPDATE_NETMASK           1177
#define IDC_ET_HEROEDIT_SKILL2XP        1177
#define IDC_UD_HEROEDIT_ARMS2XP2        1178
#define IDC_UD_HEROEDIT_SKILL2XP        1178
#define IDC_CMB_HEROEDIT_SKILL0         1179
#define IDC_CMB_HEROEDIT_SKILL1         1180
#define IDC_CMB_HEROEDIT_SKILL2         1181
#define IDC_LV_TBOX_DESC                1204
#define IDC_LV_WGEN_EDITOR              1204
#define IDC_TV_DDESC_EXPLORER           1206
#define IDC_TV_CFG_EXPLORER             1212
#define IDC_ET_WGEN_FIND                1213
#define IDC_TV_TB_EXPLORER              1214
#define IDM_RESET                       40009
#define IDM_WGEN_RESET_NTSC_M           40010
#define IDM_WGEN_RESET_NTSC_M_J         40011
#define IDM_WGEN_RESET_PAL_B            40012
#define IDM_WGEN_RESET_PAL_D            40013
#define IDM_WGEN_RESET_PAL_G            40014
#define IDM_WGEN_RESET_SECAM_D          40015
#define IDM_SAVE                        40016
#define IDM_WGEN_DEL_CFGITEM            40017
#define IDM_SYS_SYNC                    40018
#define IDM_SYS_WGEN                    40019
#define IDM_SYS_XCHG                    40021
#define IDM_SYS_PLAY                    40023
#define IDM_SYS_TBOX                    40025
#define IDM_SYS_ABOUT                   40027
#define IDM_REFRESH                     40029
#define IDM_SYNC_SYNC                   40031
#define IDM_SYNC_OPENPCDIR              40033
#define IDM_XCHG_OPEN                   40035
#define IDM_XCHG_XCHG                   40037
#define IDM_NEW                         40039
#define IDM_DOWNLOAD                    40041
#define IDM_UPLOAD                      40043
#define IDM_DELETE                      40045
#define IDM_FIND                        40046
#define IDM_OK                          40047
#define IDM_CANCEL                      40048
#define IDM_OPEN                        40049
#define IDM_IMPORT                      40050
#define IDM_EXPORT                      40051
#define IDM_BACKUP                      40052
#define IDM_FMTSETTING                  40053
#define IDM_EDIT                        40054
#define IDM_ADD                         40055
#define IDM_EXTRACT                     40056
#define IDM_PROFILE0                    40060
#define IDM_PROFILE1                    40061
#define IDM_PROFILE2                    40062
#define IDM_PROFILE3                    40063
#define IDM_PROFILE4                    40064
#define IDM_PROFILE5                    40065
#define IDM_PROFILE6                    40066
#define IDM_PROFILE7                    40067
#define IDM_PROFILE8                    40068
#define IDM_PROFILE9                    40069
#define IDM_COHERENCT_ITEM0             40070
#define IDM_COHERENCT_ITEM1             40071
#define IDM_COHERENCT_ITEM2             40072
#define IDM_COHERENCT_ITEM3             40073
#define IDM_COHERENCT_ITEM4             40074
#define IDM_COHERENCT_ITEM5             40075
#define IDM_COHERENCT_ITEM6             40076
#define IDM_COHERENCT_ITEM7             40077
#define IDM_COHERENCT_ITEM8             40078
#define IDM_COHERENCT_ITEM9             40079
#define IDM_DELETE_ITEM0                40080
#define IDM_DELETE_ITEM1                40081
#define IDM_DELETE_ITEM2                40082
#define IDM_DELETE_ITEM3                40083
#define IDM_DELETE_ITEM4                40084
#define IDM_DELETE_ITEM5                40085
#define IDM_DELETE_ITEM6                40086
#define IDM_DELETE_ITEM7                40087
#define IDM_DELETE_ITEM8                40088
#define IDM_DELETE_ITEM9                40089
#define IDM_GENERATE_ITEM0              40090
#define IDM_GENERATE_ITEM1              40091
#define IDM_GENERATE_ITEM2              40092
#define IDM_GENERATE_ITEM3              40093
#define IDM_GENERATE_ITEM4              40094
#define IDM_GENERATE_ITEM5              40095
#define IDM_GENERATE_ITEM6              40096
#define IDM_GENERATE_ITEM7              40097
#define IDM_GENERATE_ITEM8              40098
#define IDM_GENERATE_ITEM9              40099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         40100
#define _APS_NEXT_CONTROL_VALUE         1215
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
